/**
 * MIG-7.2 base — CortexConfig schema tests.
 *
 * Covers the structural invariants from architecture §9.1 + §9.3:
 *   - principal: { id } is required, every other principal field optional
 *   - agents[] must contain ≥1 entry with unique ids
 *   - each agent needs ≥1 presence block
 *   - agent ids must be lowercase alphanumeric
 *   - trust references are by agent id (string only — registry validates resolution)
 *   - renderers[] discriminated union honours `kind`
 *   - nats.url protocol gate
 *   - nats.identity.publicKey NKey format
 */

import { describe, test, expect } from "bun:test";

import { AgentConfigSchema } from "../config";
import {
  AgentDetectionSchema,
  AgentSchema,
  AttachmentsConfigSchema,
  ClaudeConfigSchema,
  CortexConfigSchema,
  DashboardRendererSchema,
  ExecutionConfigSchema,
  GithubConfigSchema,
  NatsConfigSchema,
  NatsIdentitySchema,
  PrincipalConfigSchema,
  PagerDutyRendererSchema,
  PathsConfigSchema,
  PolicyFederatedRegistrySchema,
  PolicyFederatedSchema,
  RendererSchema,
} from "../cortex-config";

// =============================================================================
// Fixture builders — minimal valid shapes
// =============================================================================

/**
 * A syntactically-valid NKey user-identifier: `U` + 55 base32 chars
 * (RFC-4648 alphabet `A-Z2-7`). Real keys are generated by the `nkeys` lib;
 * tests just need the regex to pass.
 */
const VALID_NKEY = "U" + "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567ABCDEFGHIJKLMNOPQRSTUVZ"; // 1 + 55 = 56

function minOperator() {
  return { id: "andreas" };
}

function minDiscordPresence() {
  return {
    token: "discord-bot-token",
    guildId: "1487000000000000000",
    agentChannelId: "1487000000000000001",
    logChannelId: "1487000000000000002",
  };
}

function minAgent(overrides: Record<string, unknown> = {}) {
  return {
    id: "luna",
    displayName: "Luna",
    persona: "./personas/luna.md",
    presence: { discord: minDiscordPresence() },
    ...overrides,
  };
}

function minConfig() {
  return {
    principal: minOperator(),
    agents: [minAgent()],
    claude: {},
  };
}

// =============================================================================
// Principal schema
// =============================================================================

describe("PrincipalConfigSchema", () => {
  test("requires id", () => {
    expect(() => PrincipalConfigSchema.parse({})).toThrow();
  });

  test("rejects uppercase id", () => {
    expect(() => PrincipalConfigSchema.parse({ id: "Andreas" })).toThrow(/lowercase/);
  });

  test("rejects id with dots (would break NATS subject segmentation)", () => {
    expect(() => PrincipalConfigSchema.parse({ id: "andreas.private" })).toThrow();
  });

  test("rejects id with whitespace", () => {
    expect(() => PrincipalConfigSchema.parse({ id: "andreas dev" })).toThrow();
  });

  test("rejects id with NATS wildcards", () => {
    expect(() => PrincipalConfigSchema.parse({ id: "andreas*" })).toThrow();
    expect(() => PrincipalConfigSchema.parse({ id: "andreas>" })).toThrow();
  });

  test("accepts lowercase alphanumeric + hyphen", () => {
    const parsed = PrincipalConfigSchema.parse({ id: "andreas-dev-2026" });
    expect(parsed.id).toBe("andreas-dev-2026");
  });

  // ---------------------------------------------------------------------
  // cortex#141 — letter-prefix rule (unified with StackConfigSchema)
  // ---------------------------------------------------------------------

  test("accepts canonical letter-prefixed principal ids", () => {
    // The realistic principal population — all letter-prefixed today.
    expect(PrincipalConfigSchema.parse({ id: "andreas" }).id).toBe("andreas");
    expect(PrincipalConfigSchema.parse({ id: "jcfischer" }).id).toBe("jcfischer");
    expect(PrincipalConfigSchema.parse({ id: "metafactory" }).id).toBe("metafactory");
    expect(PrincipalConfigSchema.parse({ id: "team-research" }).id).toBe("team-research");
  });

  test("accepts principal id with internal digits (only the prefix is gated)", () => {
    // The rule is letter-PREFIX, not letter-only. Internal digits are fine
    // — `team-42-research`, `andreas-2026` etc. round-trip through both
    // schemas after cortex#141 closes the gap.
    expect(PrincipalConfigSchema.parse({ id: "team-42-research" }).id).toBe("team-42-research");
    expect(PrincipalConfigSchema.parse({ id: "andreas-2026" }).id).toBe("andreas-2026");
    expect(PrincipalConfigSchema.parse({ id: "a1" }).id).toBe("a1");
  });

  test("rejects digit-prefix principal id (cortex#141 — letter-prefix rule)", () => {
    // The unified grammar requires letter-prefix on both `PrincipalConfigSchema.id`
    // and `StackConfigSchema.id` segments. A digit-prefix id like `"2andreas"`
    // would default-derive to `"2andreas/default"` — a string the stack
    // schema rejects. Fail fast at the upstream Zod gate with an actionable
    // error message rather than letting the divergence surface later at
    // subject-derivation or self-consistency-check time.
    expect(() => PrincipalConfigSchema.parse({ id: "2andreas" })).toThrow(
      /starting with a letter/,
    );
    // The error message MUST surface the migration hint so principals see
    // what to do, not just what's wrong.
    expect(() => PrincipalConfigSchema.parse({ id: "2andreas" })).toThrow(
      /team2andreas|andreas-2026/,
    );
  });

  test("rejects all-digit principal id", () => {
    expect(() => PrincipalConfigSchema.parse({ id: "123" })).toThrow(
      /starting with a letter/,
    );
  });

  test("rejects hyphen-prefix principal id (must start with a letter, not punctuation)", () => {
    expect(() => PrincipalConfigSchema.parse({ id: "-andreas" })).toThrow(
      /starting with a letter/,
    );
  });

  test("defaults dataResidency to NZ", () => {
    const parsed = PrincipalConfigSchema.parse({ id: "andreas" });
    expect(parsed.dataResidency).toBe("NZ");
  });

  test("accepts optional discordId / mattermostId / displayName", () => {
    const parsed = PrincipalConfigSchema.parse({
      id: "andreas",
      displayName: "Andreas Astrom",
      discordId: "1134000000000000000",
      mattermostId: "abc123def456",
    });
    expect(parsed.displayName).toBe("Andreas Astrom");
    expect(parsed.discordId).toBe("1134000000000000000");
    expect(parsed.mattermostId).toBe("abc123def456");
  });

  test("accepts explicit dataResidency override", () => {
    const parsed = PrincipalConfigSchema.parse({ id: "andreas", dataResidency: "CH" });
    expect(parsed.dataResidency).toBe("CH");
  });

  test("rejects malformed dataResidency (Holly W2-4)", () => {
    // ISO-3166-1 alpha-2 is exactly 2 uppercase ASCII chars.
    expect(() => PrincipalConfigSchema.parse({ id: "andreas", dataResidency: "CHE" })).toThrow();
    expect(() => PrincipalConfigSchema.parse({ id: "andreas", dataResidency: "ch" })).toThrow();
    expect(() => PrincipalConfigSchema.parse({ id: "andreas", dataResidency: "Switzerland" })).toThrow();
    expect(() => PrincipalConfigSchema.parse({ id: "andreas", dataResidency: "C" })).toThrow();
  });
});

// =============================================================================
// Agent schema
// =============================================================================

describe("AgentSchema", () => {
  test("accepts minimal Discord-only agent", () => {
    const parsed = AgentSchema.parse(minAgent());
    expect(parsed.id).toBe("luna");
    // v2.0.0 (cortex#297) — `AgentSchema.roles[]` retired.
    expect(parsed.trust).toEqual([]);
    expect(parsed.presence.discord?.token).toBe("discord-bot-token");
  });

  test("rejects uppercase id", () => {
    expect(() => AgentSchema.parse(minAgent({ id: "Luna" }))).toThrow();
  });

  test("rejects id with whitespace", () => {
    expect(() => AgentSchema.parse(minAgent({ id: "my agent" }))).toThrow();
  });

  test("accepts headless agent with empty presence (cortex#245)", () => {
    // A headless agent runs CC sessions via the dispatch-listener,
    // emits envelopes onto the bus, and surfaces on the dashboard,
    // but has no human-facing platform. Valid for the multi-stack
    // pattern (cortex#244) where a second stack is bus-only until
    // its platform presence is wired in.
    const parsed = AgentSchema.parse({
      id: "luna",
      displayName: "Luna",
      persona: "./personas/luna.md",
      presence: {},
    });
    expect(parsed.id).toBe("luna");
    expect(parsed.presence).toEqual({});
  });

  // ---------------------------------------------------------------------
  // cortex#145 — letter-prefix rule (closes the principal/stack/agent
  // letter-prefix trilogy: cortex#141 → cortex#144 → cortex#145)
  // ---------------------------------------------------------------------

  test("accepts canonical letter-prefixed agent ids", () => {
    // The realistic agent population — all letter-prefixed today.
    expect(AgentSchema.parse(minAgent({ id: "luna" })).id).toBe("luna");
    expect(AgentSchema.parse(minAgent({ id: "echo" })).id).toBe("echo");
    expect(AgentSchema.parse(minAgent({ id: "team-research" })).id).toBe("team-research");
  });

  test("accepts agent id with internal digits (only the prefix is gated)", () => {
    // The rule is letter-PREFIX, not letter-only. Internal digits are fine
    // — `agent-2026`, `team-42-research` etc.
    expect(AgentSchema.parse(minAgent({ id: "agent-2026" })).id).toBe("agent-2026");
    expect(AgentSchema.parse(minAgent({ id: "team-42-research" })).id).toBe("team-42-research");
    expect(AgentSchema.parse(minAgent({ id: "a1" })).id).toBe("a1");
  });

  test("rejects digit-prefix agent id (cortex#145 — letter-prefix rule)", () => {
    // The unified grammar requires letter-prefix on all three of
    // `PrincipalConfigSchema.id`, `StackConfigSchema.id` segments, and
    // `AgentSchema.id`. Agent ids end up embedded in NATS subjects
    // post-A.5.5 (`local.{op}.{stack}.dispatch.{agent}.>`); digit-prefix
    // segments interact poorly with downstream pattern-matchers.
    expect(() => AgentSchema.parse(minAgent({ id: "2agent" }))).toThrow(
      /starting with a letter/,
    );
    // The error message MUST surface the migration hint so principals see
    // what to do, not just what's wrong.
    expect(() => AgentSchema.parse(minAgent({ id: "2agent" }))).toThrow(
      /team-2agent|agent-2026/,
    );
  });

  test("rejects digit-prefix-with-hyphen agent id", () => {
    expect(() => AgentSchema.parse(minAgent({ id: "7-luna" }))).toThrow(
      /starting with a letter/,
    );
  });

  test("rejects all-digit agent id (Discord-snowflake paste-bug)", () => {
    expect(() => AgentSchema.parse(minAgent({ id: "1497204875912609844" }))).toThrow(
      /starting with a letter/,
    );
  });

  test("rejects hyphen-prefix agent id (must start with a letter, not punctuation)", () => {
    expect(() => AgentSchema.parse(minAgent({ id: "-luna" }))).toThrow(
      /starting with a letter/,
    );
  });

  test("accepts trust list of agent ids (no resolution)", () => {
    const parsed = AgentSchema.parse(minAgent({ trust: ["echo", "holly"] }));
    expect(parsed.trust).toEqual(["echo", "holly"]);
  });

  test("rejects trust entries that aren't agent ids (Holly W2-3; tightened by cortex#145)", () => {
    // Common typo / paste-bug: putting a Discord user id into the trust list.
    // Schema catches it with the same `^[a-z][a-z0-9-]*$` regex as agent ids
    // (principal/stack/agent letter-prefix trilogy closed by cortex#145). The
    // letter-prefix rule catches the digit-only Discord-snowflake paste-bug
    // deterministically — pre-#145 the regex was `^[a-z0-9-]+$` and digit-only
    // entries silently slipped past the structural check.
    expect(() => AgentSchema.parse(minAgent({
      trust: ["echo", "1497898452351455393"], // ← Discord id, all digits
    }))).toThrow(/starting with a letter/);
    expect(() => AgentSchema.parse(minAgent({ trust: ["Echo"] }))).toThrow();
    expect(() => AgentSchema.parse(minAgent({ trust: ["echo bot"] }))).toThrow();
    expect(() => AgentSchema.parse(minAgent({ trust: ["echo.bot"] }))).toThrow();
    expect(() => AgentSchema.parse(minAgent({ trust: ["<@1497>"] }))).toThrow();
  });

  test("rejects digit-prefix trust entry with migration hint (cortex#145)", () => {
    expect(() => AgentSchema.parse(minAgent({ trust: ["2agent"] }))).toThrow(
      /starting with a letter/,
    );
    expect(() => AgentSchema.parse(minAgent({ trust: ["2agent"] }))).toThrow(
      /team-2agent|agent-2026/,
    );
  });

  test("rejects hyphen-prefix trust entry", () => {
    expect(() => AgentSchema.parse(minAgent({ trust: ["-echo"] }))).toThrow(
      /starting with a letter/,
    );
  });

  test("accepts both discord and mattermost presence on same agent", () => {
    const parsed = AgentSchema.parse(minAgent({
      presence: {
        discord: minDiscordPresence(),
        mattermost: {
          callbackPort: 8081,
          apiUrl: "https://mm.example.com",
          apiToken: "mm-token",
        },
      },
    }));
    expect(parsed.presence.discord).toBeDefined();
    expect(parsed.presence.mattermost?.apiUrl).toBe("https://mm.example.com");
  });

  test("defaults DiscordPresence.enabled to true", () => {
    const parsed = AgentSchema.parse(minAgent());
    expect(parsed.presence.discord?.enabled).toBe(true);
  });

  test("DiscordPresence accepts numeric guildId via coerce", () => {
    const parsed = AgentSchema.parse(minAgent({
      presence: { discord: { ...minDiscordPresence(), guildId: 1487 } },
    }));
    expect(parsed.presence.discord?.guildId).toBe("1487");
  });
});

// =============================================================================
// Renderer schemas
// =============================================================================

describe("RendererSchema", () => {
  test("dashboard renderer parses with kind + defaults", () => {
    const parsed = DashboardRendererSchema.parse({ kind: "dashboard" });
    expect(parsed.port).toBe(8767);
    expect(parsed.subscribe).toEqual(["local.{principal}.>"]);
    expect(parsed.projections).toEqual([]);
  });

  test("pagerduty renderer requires routingKey", () => {
    expect(() => PagerDutyRendererSchema.parse({ kind: "pagerduty" })).toThrow();
    const parsed = PagerDutyRendererSchema.parse({
      kind: "pagerduty",
      routingKey: "PD-ROUTING-KEY",
      subscribe: ["local.{principal}.system.adapter.degraded"],
    });
    expect(parsed.routingKey).toBe("PD-ROUTING-KEY");
  });

  test("discriminated union dispatches on kind", () => {
    const dashboard = RendererSchema.parse({ kind: "dashboard" });
    expect(dashboard.kind).toBe("dashboard");

    const cliTail = RendererSchema.parse({ kind: "cli-tail" });
    expect(cliTail.kind).toBe("cli-tail");
  });

  test("unknown kind is rejected", () => {
    expect(() => RendererSchema.parse({ kind: "telegram" })).toThrow();
  });

  test("webhook-out renderer requires url", () => {
    expect(() => RendererSchema.parse({ kind: "webhook-out" })).toThrow();
    const parsed = RendererSchema.parse({
      kind: "webhook-out",
      url: "https://example.com/cortex-hook",
    });
    expect(parsed.kind).toBe("webhook-out");
  });
});

// =============================================================================
// NATS schema
// =============================================================================

describe("NatsConfigSchema", () => {
  test("rejects http:// url", () => {
    expect(() => NatsConfigSchema.parse({ url: "http://localhost:4222" })).toThrow();
  });

  test("accepts nats:// url with defaults", () => {
    const parsed = NatsConfigSchema.parse({ url: "nats://localhost:4222" });
    expect(parsed.name).toBe("cortex");
    expect(parsed.subjects).toEqual([]);
  });

  test("accepts tls:// url", () => {
    const parsed = NatsConfigSchema.parse({ url: "tls://nats.example.com:4222" });
    expect(parsed.url).toBe("tls://nats.example.com:4222");
  });

  test("NatsIdentity rejects non-NKey publicKey", () => {
    expect(() => NatsIdentitySchema.parse({
      seedPath: "/etc/cortex/operator.nk",
      publicKey: "not-an-nkey",
    })).toThrow();
  });

  test("NatsIdentity rejects short NKey-shaped strings (Holly review)", () => {
    // Real NATS NKey user keys are exactly 56 chars (U + 55 base32). Short
    // placeholders like "U1" or "UABCDEF1234567890" must be rejected so a
    // typo at config time fails fast, not silently at NatsLink.connect.
    expect(() => NatsIdentitySchema.parse({
      seedPath: "/etc/cortex/operator.nk",
      publicKey: "U1",
    })).toThrow();
    expect(() => NatsIdentitySchema.parse({
      seedPath: "/etc/cortex/operator.nk",
      publicKey: "UABCDEF1234567890",
    })).toThrow();
  });

  test("NatsIdentity rejects lowercase / base32-incompatible chars", () => {
    // NKey base32 alphabet is A-Z 2-7 (RFC-4648). Lowercase, 0, 1, 8, 9 are
    // not in the alphabet; only the U prefix + 55 valid chars pass.
    const valid55 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567" + "ABCDEFGHIJKLMNOPQRSTUV"; // 32 + 22 = 54... need 55
    const full = "U" + (valid55 + "Z");
    expect(full).toHaveLength(56);
    const parsed = NatsIdentitySchema.parse({
      seedPath: "/etc/cortex/operator.nk",
      publicKey: full,
    });
    expect(parsed.publicKey).toBe(full);

    expect(() => NatsIdentitySchema.parse({
      seedPath: "/etc/cortex/operator.nk",
      publicKey: "U" + "abcdefghijklmnopqrstuvwxyz".padEnd(55, "A"),
    })).toThrow();
  });

  // C-108 (Prereq B for cortex#67): the account signing key path field is
  // optional, accepts a string path, and parses through unchanged. We don't
  // validate the path's contents at schema time — that's the loader's job
  // (`src/common/config/account-signing-key.ts`). Schema only carries the
  // shape; runtime owns the chmod + prefix gates.

  test("accountSigningKeyPath is optional (absent → undefined)", () => {
    const parsed = NatsConfigSchema.parse({ url: "nats://localhost:4222" });
    expect(parsed.accountSigningKeyPath).toBeUndefined();
  });

  test("accountSigningKeyPath accepts a string path", () => {
    const parsed = NatsConfigSchema.parse({
      url: "nats://localhost:4222",
      accountSigningKeyPath: "/etc/cortex/account-signing.nk",
    });
    expect(parsed.accountSigningKeyPath).toBe("/etc/cortex/account-signing.nk");
  });

  test("accountSigningKeyPath rejects non-string", () => {
    expect(() => NatsConfigSchema.parse({
      url: "nats://localhost:4222",
      accountSigningKeyPath: 42,
    })).toThrow();
  });

  // ─── credsPath (cortex#86) ─────────────────────────────────────────────
  // Path is just a string at the schema layer; chmod 600 + ~/ expansion +
  // file-read live in the NatsLink loader (`../bus/nats/connection.ts`).
  // Schema only carries shape so legacy + cortex config loaders agree.

  test("credsPath is optional (absent → undefined)", () => {
    const parsed = NatsConfigSchema.parse({ url: "nats://localhost:4222" });
    expect(parsed.credsPath).toBeUndefined();
  });

  test("credsPath accepts an absolute path", () => {
    const parsed = NatsConfigSchema.parse({
      url: "nats://localhost:4222",
      credsPath: "/etc/cortex/cortex.creds",
    });
    expect(parsed.credsPath).toBe("/etc/cortex/cortex.creds");
  });

  test("credsPath accepts a ~/ path (expansion happens in loader, not schema)", () => {
    const parsed = NatsConfigSchema.parse({
      url: "nats://localhost:4222",
      credsPath: "~/.config/nats/cortex.creds",
    });
    expect(parsed.credsPath).toBe("~/.config/nats/cortex.creds");
  });

  test("credsPath rejects non-string", () => {
    expect(() => NatsConfigSchema.parse({
      url: "nats://localhost:4222",
      credsPath: 42,
    })).toThrow();
  });
});

// =============================================================================
// AgentConfigSchema.nats.accountSigningKeyPath — MIRROR of cortex-config field
// =============================================================================
//
// We MIRROR the field across both schemas during the MIG-7.2 overlap window.
// Asserting the legacy schema accepts it (and round-trips it) protects against
// drift — if someone edits one schema and forgets the other, this test fails.

describe("AgentConfigSchema.nats.accountSigningKeyPath (MIRROR)", () => {
  /** Minimal AgentConfig shell to exercise the optional `nats` block. */
  function minAgentConfig(natsExtras: Record<string, unknown> = {}) {
    return {
      agent: { name: "test", displayName: "Test", operatorId: "op" },
      discord: [],
      mattermost: [],
      claude: { timeoutMs: 1000 },
      paths: { publishedEventsDir: "/tmp/x" },
      nats: {
        url: "nats://localhost:4222",
        ...natsExtras,
      },
    };
  }

  test("absent on legacy AgentConfig.nats → undefined", () => {
    const parsed = AgentConfigSchema.parse(minAgentConfig());
    expect(parsed.nats?.accountSigningKeyPath).toBeUndefined();
  });

  test("accepts a string path on legacy AgentConfig.nats", () => {
    const parsed = AgentConfigSchema.parse(
      minAgentConfig({ accountSigningKeyPath: "/etc/cortex/account-signing.nk" }),
    );
    expect(parsed.nats?.accountSigningKeyPath).toBe("/etc/cortex/account-signing.nk");
  });

  test("credsPath (cortex#86) mirrors onto AgentConfig.nats", () => {
    const parsed = AgentConfigSchema.parse(
      minAgentConfig({ credsPath: "~/.config/nats/cortex.creds" }),
    );
    expect(parsed.nats?.credsPath).toBe("~/.config/nats/cortex.creds");
  });

  test("credsPath rejects non-string on legacy AgentConfig.nats", () => {
    expect(() =>
      AgentConfigSchema.parse(minAgentConfig({ credsPath: 42 })),
    ).toThrow();
  });

  test("rejects non-string on legacy AgentConfig.nats", () => {
    expect(() => AgentConfigSchema.parse(
      minAgentConfig({ accountSigningKeyPath: 42 }),
    )).toThrow();
  });
});

// =============================================================================
// Renderer URL validation
// =============================================================================

describe("DashboardRendererSchema.publicUrl", () => {
  test("accepts a valid https URL", () => {
    const parsed = DashboardRendererSchema.parse({
      kind: "dashboard",
      publicUrl: "https://cortex.meta-factory.ai",
    });
    expect(parsed.publicUrl).toBe("https://cortex.meta-factory.ai");
  });

  test("rejects a non-URL string", () => {
    expect(() => DashboardRendererSchema.parse({
      kind: "dashboard",
      publicUrl: "not a url",
    })).toThrow();
  });
});

describe("WebhookOutRenderer.url", () => {
  test("rejects a non-URL string", () => {
    expect(() => RendererSchema.parse({
      kind: "webhook-out",
      url: "not-a-url",
    })).toThrow();
  });
});

// =============================================================================
// Cross-cutting schemas — minimal standalone tests
// =============================================================================

describe("Cross-cutting schemas — defaults populated by emptyDefault helper", () => {
  test("ClaudeConfigSchema applies inner defaults", () => {
    const parsed = ClaudeConfigSchema.parse({});
    expect(parsed.timeoutMs).toBe(120_000);
    expect(parsed.asyncTimeoutMs).toBe(900_000);
    expect(parsed.allowedTools).toEqual([]);
    expect(parsed.allowedDirs).toEqual([]);
  });

  test("AttachmentsConfigSchema applies inner defaults", () => {
    const parsed = AttachmentsConfigSchema.parse({});
    expect(parsed.enabled).toBe(true);
    expect(parsed.maxFileSizeBytes).toBe(10 * 1024 * 1024);
  });

  test("ExecutionConfigSchema applies inner defaults", () => {
    const parsed = ExecutionConfigSchema.parse({});
    expect(parsed.default).toBe("local");
    expect(parsed.backends).toEqual([]);
  });

  test("GithubConfigSchema applies inner defaults via emptyDefault for agentDetection", () => {
    const parsed = GithubConfigSchema.parse({});
    expect(parsed.webhookSecret).toBe("");
    expect(parsed.repos).toEqual([]);
    expect(parsed.agentDetection.commitTrailers).toEqual(["Co-Authored-By: Claude"]);
  });

  test("PathsConfigSchema applies inner defaults", () => {
    const parsed = PathsConfigSchema.parse({});
    expect(parsed.publishedEventsDir).toBe("~/.claude/events/published");
    expect(parsed.logDir).toBe("~/.config/cortex/logs");
  });

  test("AgentDetectionSchema applies inner defaults", () => {
    const parsed = AgentDetectionSchema.parse({});
    expect(parsed.branchPatterns).toEqual(["^feat/(g|f|i)-\\d+"]);
    expect(parsed.commentPatterns).toEqual(["^Starting:", "^Completed:"]);
  });
});

// =============================================================================
// CortexConfig — top-level invariants
// =============================================================================

describe("CortexConfigSchema", () => {
  test("accepts minimal valid config", () => {
    const parsed = CortexConfigSchema.parse(minConfig());
    expect(parsed.principal.id).toBe("andreas");
    expect(parsed.agents).toHaveLength(1);
    expect(parsed.renderers).toEqual([]);
  });

  test("rejects empty agents[]", () => {
    expect(() => CortexConfigSchema.parse({
      ...minConfig(),
      agents: [],
    })).toThrow(/at least one agent/);
  });

  test("rejects duplicate agent ids", () => {
    expect(() => CortexConfigSchema.parse({
      ...minConfig(),
      agents: [minAgent({ id: "luna" }), minAgent({ id: "luna" })],
    })).toThrow(/agent ids must be unique/);
  });

  test("accepts full multi-agent + renderers + nats config", () => {
    const parsed = CortexConfigSchema.parse({
      principal: {
        id: "andreas",
        displayName: "Andreas Astrom",
        discordId: "1134000000000000000",
      },
      agents: [
        minAgent({ id: "luna", roles: ["operator"], trust: ["echo", "holly"] }),
        minAgent({ id: "echo", roles: ["agent-restricted"], trust: ["luna", "holly"] }),
        minAgent({ id: "holly", roles: ["agent-restricted"], trust: ["luna"] }),
      ],
      renderers: [
        { kind: "dashboard", port: 8767, publicUrl: "https://cortex.meta-factory.ai" },
        { kind: "pagerduty", routingKey: "PD-KEY", subscribe: ["local.{principal}.system.>"] },
      ],
      claude: {},
      nats: {
        url: "nats://localhost:4222",
        subjects: ["local.{principal}.>"],
        identity: {
          seedPath: "/etc/cortex/andreas.nk",
          publicKey: VALID_NKEY,
        },
      },
    });

    expect(parsed.agents).toHaveLength(3);
    expect(parsed.renderers).toHaveLength(2);
    expect(parsed.nats?.identity?.publicKey).toBe(VALID_NKEY);

    const dashboard = parsed.renderers.find((r) => r.kind === "dashboard");
    expect(dashboard?.kind === "dashboard" && dashboard.publicUrl).toBe(
      "https://cortex.meta-factory.ai",
    );
  });

  test("trust list is preserved verbatim (no resolution at schema layer)", () => {
    // Coupling rule §9.3: schema accepts trust as strings; the agent registry
    // (MIG-7.2a) validates that the referenced ids exist. Schema must not
    // pre-empt that responsibility.
    const parsed = CortexConfigSchema.parse({
      ...minConfig(),
      agents: [minAgent({ trust: ["echo", "ghost-agent-that-doesnt-exist"] })],
    });
    expect(parsed.agents[0]?.trust).toEqual(["echo", "ghost-agent-that-doesnt-exist"]);
  });

  test("defaults are applied for optional top-level blocks (Holly W2 — emptyDefault closes Zod quirk)", () => {
    // Before MIG-7.2 rev 2: outer `.default({} as any)` did NOT re-parse the
    // default through the inner schema, so omitting `attachments` gave `{}`
    // literally instead of `{ enabled: true, ... }`. The `emptyDefault`
    // helper computes the inner-default-applied shape at load time and uses
    // it as the literal default, so omitting the field now produces the
    // populated shape that downstream code expects.
    const parsed = CortexConfigSchema.parse(minConfig());
    expect(parsed.attachments.enabled).toBe(true);
    expect(parsed.attachments.maxFileSizeBytes).toBe(10 * 1024 * 1024);
    expect(parsed.execution.default).toBe("local");
    expect(parsed.github.webhookSecret).toBe("");
    expect(parsed.github.agentDetection.commitTrailers).toEqual(["Co-Authored-By: Claude"]);
    expect(parsed.paths.publishedEventsDir).toBe("~/.claude/events/published");
    expect(parsed.paths.logDir).toBe("~/.config/cortex/logs");
    expect(parsed.networksDir).toBe("./networks");
  });

  test("rejects legacy `agent:` (singular) field with a migration error (Holly W2-1)", () => {
    // The new schema has no `agent:` block (that's grove-v2's shape). Round-1
    // relied on Zod's silent unknown-key strip; round-2 flags this as a real
    // migration safety gap — principals who hand-edit a partial cortex.yaml
    // get no feedback that the legacy field is being ignored.
    //
    // Fix: the `agent` slot is now `z.never()` with an explicit error pointing
    // at `migrate-config` (MIG-7.2e). A config carrying both `agent:{}` and
    // `agents:[]` fails at parse time with a clear migration error.
    expect(() => CortexConfigSchema.parse({
      ...minConfig(),
      agent: { name: "luna", displayName: "Luna" },
    })).toThrow(/legacy `agent:`/);
  });

  test("rejects legacy `trustedAgentBots:` field with a migration error (Holly W2-1)", () => {
    // Same migration-safety rationale as the `agent:` anti-field — legacy
    // grove-v2 had a top-level `trustedAgentBots:` block that's now expressed
    // per-agent as `trust:[]`. The schema rejects the legacy shape so a
    // hand-migration miss surfaces at config load.
    expect(() => CortexConfigSchema.parse({
      ...minConfig(),
      trustedAgentBots: ["echo", "holly"],
    })).toThrow(/legacy `trustedAgentBots:`/);
  });

  test("rejects legacy top-level `discord:` array with a migration error (Holly W3)", () => {
    // Top-level `discord:[]` was the grove-v2 sibling of `agent:`. In cortex,
    // per-instance credentials live under `agents[<id>].presence.discord`.
    // Without this guard, a hand-migration miss strips the legacy block
    // silently and the principal gets a headless agent without an obvious
    // migration signal (cortex#245 removed the per-agent "at least one
    // presence" refine, so headless is no longer a useful proxy alert).
    expect(() => CortexConfigSchema.parse({
      ...minConfig(),
      discord: [{ token: "x", guildId: "1", agentChannelId: "2", logChannelId: "3" }],
    })).toThrow(/legacy top-level `discord:`/);
    expect(() => CortexConfigSchema.parse({
      ...minConfig(),
      discord: [{ token: "x", guildId: "1", agentChannelId: "2", logChannelId: "3" }],
    })).toThrow(/agents\[<id>\]\.presence\.discord/);
  });

  test("rejects legacy top-level `mattermost:` array with a migration error (Holly W3)", () => {
    // Same migration-safety rationale as the `discord:` anti-field above.
    expect(() => CortexConfigSchema.parse({
      ...minConfig(),
      mattermost: [{ apiUrl: "https://mm.example.com", apiToken: "tok" }],
    })).toThrow(/legacy top-level `mattermost:`/);
    expect(() => CortexConfigSchema.parse({
      ...minConfig(),
      mattermost: [{ apiUrl: "https://mm.example.com", apiToken: "tok" }],
    })).toThrow(/agents\[<id>\]\.presence\.mattermost/);
  });
});

// =============================================================================
// MIRROR sync — cortex cross-cutting schemas vs AgentConfigSchema
// =============================================================================
//
// Six cortex schemas (Claude / Attachments / Execution / Github + AgentDetection
// / Paths) carry MIRROR breadcrumbs in their JSDoc pointing at the corresponding
// AgentConfigSchema block. The breadcrumb is a manual guard during the MIG-7.2
// overlap window — a field added on one side must be added on the other side
// too, otherwise downstream code that reads AgentConfig and writes CortexConfig
// (or vice versa) silently drops data. These tests are the structural check
// that fires automatically if the breadcrumbs are missed.
//
// Method: parse `{}` on each cortex schema, parse the minimum AgentConfig
// (which applies inner defaults to optional cross-cutting blocks), and compare.
// Default-value equality is the strictest test because it catches both field
// additions/removals AND default drift. Known divergence — `paths.logDir`
// (grove → cortex rename) — is asserted as a key-set match plus per-field
// equality on the non-divergent fields.

describe("PolicyFederatedRegistrySchema — IAW D.4.3", () => {
  test("accepts a fully populated registry block (url + pubkey)", () => {
    const r = PolicyFederatedRegistrySchema.parse({
      url: "https://network.meta-factory.ai",
      // 43-char base64 alphabet + "=" padding → 44 chars total. The
      // value here is structural only; signature paths exercise real
      // keys at the client test layer.
      pubkey: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
    });
    expect(r.url).toBe("https://network.meta-factory.ai");
    expect(r.pubkey).toBe("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=");
  });

  test("accepts a url-only block (TOFU posture)", () => {
    const r = PolicyFederatedRegistrySchema.parse({
      url: "https://network.meta-factory.ai/",
    });
    expect(r.pubkey).toBeUndefined();
  });

  test("rejects a malformed url", () => {
    expect(() =>
      PolicyFederatedRegistrySchema.parse({ url: "not-a-url" }),
    ).toThrow();
  });

  test("rejects a pubkey that isn't base64 of the right length", () => {
    expect(() =>
      PolicyFederatedRegistrySchema.parse({
        url: "https://network.meta-factory.ai",
        pubkey: "tooshort",
      }),
    ).toThrow();
  });

  test("PolicyFederatedSchema accepts an optional registry sub-block", () => {
    // Absence is allowed (no registry → no consultation).
    const without = PolicyFederatedSchema.parse({});
    expect(without.registry).toBeUndefined();
    expect(without.networks).toEqual([]);

    // Presence parses through and round-trips.
    const withReg = PolicyFederatedSchema.parse({
      networks: [],
      registry: { url: "https://network.meta-factory.ai" },
    });
    expect(withReg.registry?.url).toBe("https://network.meta-factory.ai");
  });
});

describe("MIRROR sync — cortex cross-cutting schemas vs AgentConfigSchema", () => {
  // Minimum AgentConfig that exposes inner defaults on every cross-cutting block.
  //
  // AgentConfig pre-dates the cortex-side `emptyDefault` helper, so its outer
  // `.default({} as any)` wrappers exhibit the Zod v4 quirk documented on
  // `emptyDefault`: omitting the field returns the literal `{}` rather than
  // the inner-default-applied shape. To compare populated shapes against the
  // cortex side, pass each cross-cutting block as an explicit `{}` so Zod
  // re-parses it through the inner schema and the inner defaults apply.
  const bot = AgentConfigSchema.parse({
    agent: { name: "x", displayName: "x" },
    discord: [],
    claude: {},
    attachments: {},
    execution: {},
    github: {},
    paths: {},
  });

  test("claude defaults match", () => {
    expect(ClaudeConfigSchema.parse({})).toEqual(bot.claude);
  });

  test("attachments defaults match", () => {
    expect(AttachmentsConfigSchema.parse({})).toEqual(bot.attachments);
  });

  test("execution defaults match", () => {
    expect(ExecutionConfigSchema.parse({})).toEqual(bot.execution);
  });

  test("github defaults match", () => {
    expect(GithubConfigSchema.parse({})).toEqual(bot.github);
  });

  test("agentDetection defaults match", () => {
    // Nested under github; check the inner block too so a field added inside
    // agentDetection on one side surfaces immediately rather than only via
    // the parent github diff (which `.toEqual` deep-compares, but an
    // independent assertion documents the intent).
    expect(AgentDetectionSchema.parse({})).toEqual(bot.github.agentDetection);
  });

  test("paths shape matches (logDir grove→cortex rename is the only intended divergence)", () => {
    const cortexPaths = PathsConfigSchema.parse({});
    // Same key set — field additions/removals would fail here.
    expect(Object.keys(cortexPaths).sort()).toEqual(Object.keys(bot.paths).sort());
    // Non-divergent fields equal.
    expect(cortexPaths.publishedEventsDir).toBe(bot.paths.publishedEventsDir);
    // Documented divergence: cortex moved the default log directory off the
    // grove namespace as part of the rename. If this assertion ever stops
    // holding, the AgentConfig side has been re-pointed at cortex/ too and the
    // MIRROR window is collapsing — drop both this assertion and the
    // AgentConfig.paths block (per the MIRROR-removal note in cortex-config.ts).
    expect(cortexPaths.logDir).toBe("~/.config/cortex/logs");
    expect(bot.paths.logDir).toBe("~/.config/grove/logs");
  });
});
