/**
 * MIG-7.2 base — CortexConfig schema tests.
 *
 * Covers the structural invariants from architecture §9.1 + §9.3:
 *   - principal: { id } is required, every other principal field optional
 *   - agents[] must contain ≥1 entry with unique ids
 *   - each agent needs ≥1 presence block
 *   - agent ids must be lowercase alphanumeric
 *   - trust references are by agent id (string only — registry validates resolution)
 *   - renderers[] discriminated union honours `kind`
 *   - nats.url protocol gate
 *   - nats.identity.publicKey NKey format
 */

import { describe, test, expect } from "bun:test";

import { AgentConfigSchema } from "../config";
import {
  AgentDetectionSchema,
  AgentRuntimeSchema,
  AgentSchema,
  AttachmentsConfigSchema,
  BusConfigSchema,
  BusDevImplementConfigSchema,
  ClaudeConfigSchema,
  CortexConfigSchema,
  DashboardRendererSchema,
  DiscordNotifyTargetSchema,
  ReflexTargetSchema,
  ExecutionConfigSchema,
  GithubConfigSchema,
  NatsConfigSchema,
  NatsIdentitySchema,
  PrincipalConfigSchema,
  PagerDutyRendererSchema,
  PathsConfigSchema,
  PolicyFederatedRegistrySchema,
  PolicyFederatedSchema,
  PolicyPublicSchema,
  PolicySchema,
  RendererSchema,
  WebhookOutRendererSchema,
  isFederatedSubjectInOwnScope,
  ownFederatedSubjectScopePrefix,
} from "../cortex-config";

// =============================================================================
// Fixture builders — minimal valid shapes
// =============================================================================

/**
 * A syntactically-valid NKey user-identifier: `U` + 55 base32 chars
 * (RFC-4648 alphabet `A-Z2-7`). Real keys are generated by the `nkeys` lib;
 * tests just need the regex to pass.
 */
const VALID_NKEY = "U" + "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567ABCDEFGHIJKLMNOPQRSTUVZ"; // 1 + 55 = 56

function minPrincipal() {
  return { id: "andreas" };
}

function minDiscordPresence() {
  return {
    token: "discord-bot-token",
    guildId: "1111111111111111111",
    agentChannelId: "2222222222222222222",
    logChannelId: "3333333333333333333",
  };
}

function minAgent(overrides: Record<string, unknown> = {}) {
  return {
    id: "luna",
    displayName: "Luna",
    persona: "./personas/luna.md",
    presence: { discord: minDiscordPresence() },
    ...overrides,
  };
}

function minConfig() {
  return {
    principal: minPrincipal(),
    agents: [minAgent()],
    claude: {},
  };
}

// =============================================================================
// Principal schema
// =============================================================================

describe("PrincipalConfigSchema", () => {
  test("requires id", () => {
    expect(() => PrincipalConfigSchema.parse({})).toThrow();
  });

  test("rejects uppercase id", () => {
    expect(() => PrincipalConfigSchema.parse({ id: "Andreas" })).toThrow(/lowercase/);
  });

  test("rejects id with dots (would break NATS subject segmentation)", () => {
    expect(() => PrincipalConfigSchema.parse({ id: "andreas.private" })).toThrow();
  });

  test("rejects id with whitespace", () => {
    expect(() => PrincipalConfigSchema.parse({ id: "andreas dev" })).toThrow();
  });

  test("rejects id with NATS wildcards", () => {
    expect(() => PrincipalConfigSchema.parse({ id: "andreas*" })).toThrow();
    expect(() => PrincipalConfigSchema.parse({ id: "andreas>" })).toThrow();
  });

  test("accepts lowercase alphanumeric + hyphen", () => {
    const parsed = PrincipalConfigSchema.parse({ id: "andreas-dev-2026" });
    expect(parsed.id).toBe("andreas-dev-2026");
  });

  // ---------------------------------------------------------------------
  // cortex#141 — letter-prefix rule (unified with StackConfigSchema)
  // ---------------------------------------------------------------------

  test("accepts canonical letter-prefixed principal ids", () => {
    // The realistic principal population — all letter-prefixed today.
    expect(PrincipalConfigSchema.parse({ id: "andreas" }).id).toBe("andreas");
    expect(PrincipalConfigSchema.parse({ id: "jcfischer" }).id).toBe("jcfischer");
    expect(PrincipalConfigSchema.parse({ id: "metafactory" }).id).toBe("metafactory");
    expect(PrincipalConfigSchema.parse({ id: "team-research" }).id).toBe("team-research");
  });

  test("accepts principal id with internal digits (only the prefix is gated)", () => {
    // The rule is letter-PREFIX, not letter-only. Internal digits are fine
    // — `team-42-research`, `andreas-2026` etc. round-trip through both
    // schemas after cortex#141 closes the gap.
    expect(PrincipalConfigSchema.parse({ id: "team-42-research" }).id).toBe("team-42-research");
    expect(PrincipalConfigSchema.parse({ id: "andreas-2026" }).id).toBe("andreas-2026");
    expect(PrincipalConfigSchema.parse({ id: "a1" }).id).toBe("a1");
  });

  test("rejects digit-prefix principal id (cortex#141 — letter-prefix rule)", () => {
    // The unified grammar requires letter-prefix on both `PrincipalConfigSchema.id`
    // and `StackConfigSchema.id` segments. A digit-prefix id like `"2andreas"`
    // would default-derive to `"2andreas/default"` — a string the stack
    // schema rejects. Fail fast at the upstream Zod gate with an actionable
    // error message rather than letting the divergence surface later at
    // subject-derivation or self-consistency-check time.
    expect(() => PrincipalConfigSchema.parse({ id: "2andreas" })).toThrow(
      /starting with a letter/,
    );
    // The error message MUST surface the migration hint so principals see
    // what to do, not just what's wrong.
    expect(() => PrincipalConfigSchema.parse({ id: "2andreas" })).toThrow(
      /team2andreas|andreas-2026/,
    );
  });

  test("rejects all-digit principal id", () => {
    expect(() => PrincipalConfigSchema.parse({ id: "123" })).toThrow(
      /starting with a letter/,
    );
  });

  test("rejects hyphen-prefix principal id (must start with a letter, not punctuation)", () => {
    expect(() => PrincipalConfigSchema.parse({ id: "-andreas" })).toThrow(
      /starting with a letter/,
    );
  });

  test("defaults dataResidency to NZ", () => {
    const parsed = PrincipalConfigSchema.parse({ id: "andreas" });
    expect(parsed.dataResidency).toBe("NZ");
  });

  test("accepts optional discordId / mattermostId / displayName", () => {
    const parsed = PrincipalConfigSchema.parse({
      id: "andreas",
      displayName: "Andreas Astrom",
      discordId: "5555555555555555555",
      mattermostId: "abc123def456",
    });
    expect(parsed.displayName).toBe("Andreas Astrom");
    expect(parsed.discordId).toBe("5555555555555555555");
    expect(parsed.mattermostId).toBe("abc123def456");
  });

  test("accepts explicit dataResidency override", () => {
    const parsed = PrincipalConfigSchema.parse({ id: "andreas", dataResidency: "CH" });
    expect(parsed.dataResidency).toBe("CH");
  });

  test("rejects malformed dataResidency (Holly W2-4)", () => {
    // ISO-3166-1 alpha-2 is exactly 2 uppercase ASCII chars.
    expect(() => PrincipalConfigSchema.parse({ id: "andreas", dataResidency: "CHE" })).toThrow();
    expect(() => PrincipalConfigSchema.parse({ id: "andreas", dataResidency: "ch" })).toThrow();
    expect(() => PrincipalConfigSchema.parse({ id: "andreas", dataResidency: "Switzerland" })).toThrow();
    expect(() => PrincipalConfigSchema.parse({ id: "andreas", dataResidency: "C" })).toThrow();
  });
});

// =============================================================================
// Agent schema
// =============================================================================

describe("AgentSchema", () => {
  test("accepts minimal Discord-only agent", () => {
    const parsed = AgentSchema.parse(minAgent());
    expect(parsed.id).toBe("luna");
    // v2.0.0 (cortex#297) — `AgentSchema.roles[]` retired.
    expect(parsed.trust).toEqual([]);
    expect(parsed.presence.discord?.token).toBe("discord-bot-token");
  });

  test("rejects uppercase id", () => {
    expect(() => AgentSchema.parse(minAgent({ id: "Luna" }))).toThrow();
  });

  test("rejects id with whitespace", () => {
    expect(() => AgentSchema.parse(minAgent({ id: "my agent" }))).toThrow();
  });

  test("accepts headless agent with empty presence (cortex#245)", () => {
    // A headless agent runs CC sessions via the dispatch-listener,
    // emits envelopes onto the bus, and surfaces on the dashboard,
    // but has no human-facing platform. Valid for the multi-stack
    // pattern (cortex#244) where a second stack is bus-only until
    // its platform presence is wired in.
    const parsed = AgentSchema.parse({
      id: "luna",
      displayName: "Luna",
      persona: "./personas/luna.md",
      presence: {},
    });
    expect(parsed.id).toBe("luna");
    expect(parsed.presence).toEqual({});
  });

  // ---------------------------------------------------------------------
  // cortex#145 — letter-prefix rule (closes the principal/stack/agent
  // letter-prefix trilogy: cortex#141 → cortex#144 → cortex#145)
  // ---------------------------------------------------------------------

  test("accepts canonical letter-prefixed agent ids", () => {
    // The realistic agent population — all letter-prefixed today.
    expect(AgentSchema.parse(minAgent({ id: "luna" })).id).toBe("luna");
    expect(AgentSchema.parse(minAgent({ id: "echo" })).id).toBe("echo");
    expect(AgentSchema.parse(minAgent({ id: "team-research" })).id).toBe("team-research");
  });

  test("accepts agent id with internal digits (only the prefix is gated)", () => {
    // The rule is letter-PREFIX, not letter-only. Internal digits are fine
    // — `agent-2026`, `team-42-research` etc.
    expect(AgentSchema.parse(minAgent({ id: "agent-2026" })).id).toBe("agent-2026");
    expect(AgentSchema.parse(minAgent({ id: "team-42-research" })).id).toBe("team-42-research");
    expect(AgentSchema.parse(minAgent({ id: "a1" })).id).toBe("a1");
  });

  test("rejects digit-prefix agent id (cortex#145 — letter-prefix rule)", () => {
    // The unified grammar requires letter-prefix on all three of
    // `PrincipalConfigSchema.id`, `StackConfigSchema.id` segments, and
    // `AgentSchema.id`. Agent ids end up embedded in NATS subjects
    // post-A.5.5 (`local.{op}.{stack}.dispatch.{agent}.>`); digit-prefix
    // segments interact poorly with downstream pattern-matchers.
    expect(() => AgentSchema.parse(minAgent({ id: "2agent" }))).toThrow(
      /starting with a letter/,
    );
    // The error message MUST surface the migration hint so principals see
    // what to do, not just what's wrong.
    expect(() => AgentSchema.parse(minAgent({ id: "2agent" }))).toThrow(
      /team-2agent|agent-2026/,
    );
  });

  test("rejects digit-prefix-with-hyphen agent id", () => {
    expect(() => AgentSchema.parse(minAgent({ id: "7-luna" }))).toThrow(
      /starting with a letter/,
    );
  });

  test("rejects all-digit agent id (Discord-snowflake paste-bug)", () => {
    expect(() => AgentSchema.parse(minAgent({ id: "6666666666666666666" }))).toThrow(
      /starting with a letter/,
    );
  });

  test("rejects hyphen-prefix agent id (must start with a letter, not punctuation)", () => {
    expect(() => AgentSchema.parse(minAgent({ id: "-luna" }))).toThrow(
      /starting with a letter/,
    );
  });

  test("accepts trust list of agent ids (no resolution)", () => {
    const parsed = AgentSchema.parse(minAgent({ trust: ["echo", "holly"] }));
    expect(parsed.trust).toEqual(["echo", "holly"]);
  });

  test("rejects trust entries that aren't agent ids (Holly W2-3; tightened by cortex#145)", () => {
    // Common typo / paste-bug: putting a Discord user id into the trust list.
    // Schema catches it with the same `^[a-z][a-z0-9-]*$` regex as agent ids
    // (principal/stack/agent letter-prefix trilogy closed by cortex#145). The
    // letter-prefix rule catches the digit-only Discord-snowflake paste-bug
    // deterministically — pre-#145 the regex was `^[a-z0-9-]+$` and digit-only
    // entries silently slipped past the structural check.
    expect(() => AgentSchema.parse(minAgent({
      trust: ["echo", "4444444444444444444"], // ← Discord id, all digits
    }))).toThrow(/starting with a letter/);
    expect(() => AgentSchema.parse(minAgent({ trust: ["Echo"] }))).toThrow();
    expect(() => AgentSchema.parse(minAgent({ trust: ["echo bot"] }))).toThrow();
    expect(() => AgentSchema.parse(minAgent({ trust: ["echo.bot"] }))).toThrow();
    expect(() => AgentSchema.parse(minAgent({ trust: ["<@1497>"] }))).toThrow();
  });

  test("rejects digit-prefix trust entry with migration hint (cortex#145)", () => {
    expect(() => AgentSchema.parse(minAgent({ trust: ["2agent"] }))).toThrow(
      /starting with a letter/,
    );
    expect(() => AgentSchema.parse(minAgent({ trust: ["2agent"] }))).toThrow(
      /team-2agent|agent-2026/,
    );
  });

  test("rejects hyphen-prefix trust entry", () => {
    expect(() => AgentSchema.parse(minAgent({ trust: ["-echo"] }))).toThrow(
      /starting with a letter/,
    );
  });

  test("accepts both discord and mattermost presence on same agent", () => {
    const parsed = AgentSchema.parse(minAgent({
      presence: {
        discord: minDiscordPresence(),
        mattermost: {
          callbackPort: 8081,
          apiUrl: "https://mm.example.com",
          apiToken: "mm-token",
        },
      },
    }));
    expect(parsed.presence.discord).toBeDefined();
    expect(parsed.presence.mattermost?.apiUrl).toBe("https://mm.example.com");
  });

  test("defaults DiscordPresence.enabled to true", () => {
    const parsed = AgentSchema.parse(minAgent());
    expect(parsed.presence.discord?.enabled).toBe(true);
  });

  test("DiscordPresence accepts numeric guildId via coerce", () => {
    const parsed = AgentSchema.parse(minAgent({
      presence: { discord: { ...minDiscordPresence(), guildId: 1487 } },
    }));
    expect(parsed.presence.discord?.guildId).toBe("1487");
  });

  // ---------------------------------------------------------------------
  // cortex#1720 S1 — optional `state:` field (opt-in instance state)
  // ---------------------------------------------------------------------

  test("stateless by default — a fragment WITHOUT state parses, state is undefined", () => {
    const parsed = AgentSchema.parse(minAgent());
    expect(parsed.state).toBeUndefined();
  });

  test("accepts a fragment declaring state: { blueprint, version }", () => {
    const parsed = AgentSchema.parse(
      minAgent({ state: { blueprint: "AgentState", version: ">=0.1.0" } }),
    );
    expect(parsed.state).toEqual({ blueprint: "AgentState", version: ">=0.1.0" });
  });

  test("rejects a state block missing blueprint", () => {
    expect(() =>
      AgentSchema.parse(minAgent({ state: { version: ">=0.1.0" } })),
    ).toThrow();
  });

  test("rejects a state block missing version", () => {
    expect(() =>
      AgentSchema.parse(minAgent({ state: { blueprint: "AgentState" } })),
    ).toThrow();
  });

  test("rejects empty-string blueprint / version", () => {
    expect(() =>
      AgentSchema.parse(minAgent({ state: { blueprint: "", version: ">=0.1.0" } })),
    ).toThrow();
    expect(() =>
      AgentSchema.parse(minAgent({ state: { blueprint: "AgentState", version: "" } })),
    ).toThrow();
  });
});

// =============================================================================
// Bot Packs B-1 — AgentRuntime.brain block (docs/design-bot-packs.md §4)
// =============================================================================

describe("AgentRuntimeSchema.brain (Bot Packs B-1)", () => {
  function minRuntime(brain?: Record<string, unknown>) {
    return {
      mode: "in-process" as const,
      capabilities: ["soc.compose.flow"],
      ...(brain !== undefined && { brain }),
    };
  }

  test("brain absent ⇒ builtin ⇒ existing runtime parses with no brain key", () => {
    // The zero-migration contract: a runtime that omits `brain` parses with an
    // UNDEFINED `brain` field — no synthetic default object, so downstream
    // engine resolution stays untouched.
    const parsed = AgentRuntimeSchema.parse(minRuntime());
    expect(parsed.brain).toBeUndefined();
  });

  test("representative existing config shapes parse identically (builtin-absent equivalence spread) (no brain drift)", () => {
    // Prove the schema addition is purely additive: a representative spread of
    // pre-B-1 runtime shapes round-trips byte-identical, with `brain` absent.
    const fixtures: Record<string, unknown>[] = [
      { mode: "in-process", capabilities: [] },
      { mode: "in-process", capabilities: ["code-review.typescript"], engine: "assistant" },
      { mode: "standalone", capabilities: ["research"], substrate: "claude-code" },
      { mode: "in-process", capabilities: ["code-review"], engine: "sage", model: "pi" },
      { mode: "in-process", capabilities: ["x"], maxConcurrent: 3, modelClass: "frontier", sovereignty: "selective" },
    ];
    for (const fx of fixtures) {
      const parsed = AgentRuntimeSchema.parse(fx);
      expect(parsed.brain).toBeUndefined();
      // The non-brain fields survive verbatim (a sample of each).
      expect(parsed.mode).toBe(fx.mode as "in-process" | "standalone");
      expect(parsed.capabilities).toEqual(fx.capabilities as string[]);
    }
  });

  test("brain defaults: kind=builtin, protocol=cortex-brain/v1, lifecycle=per-task, secrets=[], dispatch_capabilities=[], maxRestarts=3", () => {
    const parsed = AgentRuntimeSchema.parse(minRuntime({}));
    expect(parsed.brain).toEqual({
      kind: "builtin",
      protocol: "cortex-brain/v1",
      lifecycle: "per-task",
      secrets: [],
      dispatch_capabilities: [],
      maxRestarts: 3,
    });
  });

  test("kind=exec requires run", () => {
    expect(() => AgentRuntimeSchema.parse(minRuntime({ kind: "exec" }))).toThrow(
      /brain\.run is required when brain\.kind is 'exec'/,
    );
  });

  test("kind=exec with run parses + carries the run/secrets/dispatch allow-list", () => {
    const parsed = AgentRuntimeSchema.parse(
      minRuntime({
        kind: "exec",
        run: "bun {pack}/brain/main.ts",
        secrets: ["VT_API_KEY"],
        dispatch_capabilities: ["soc.triage.email"],
      }),
    );
    expect(parsed.brain?.kind).toBe("exec");
    expect(parsed.brain?.run).toBe("bun {pack}/brain/main.ts");
    expect(parsed.brain?.secrets).toEqual(["VT_API_KEY"]);
    expect(parsed.brain?.dispatch_capabilities).toEqual(["soc.triage.email"]);
  });

  test("lifecycle=daemon is now ACCEPTED at load (B-2 daemon host is live)", () => {
    const parsed = AgentRuntimeSchema.parse(
      minRuntime({
        kind: "exec",
        run: "bun x.ts",
        lifecycle: "daemon",
        maxRestarts: 5,
      }),
    );
    expect(parsed.brain?.lifecycle).toBe("daemon");
    expect(parsed.brain?.maxRestarts).toBe(5);
  });

  test("lifecycle defaults to per-task when omitted", () => {
    const parsed = AgentRuntimeSchema.parse(
      minRuntime({ kind: "exec", run: "bun x.ts" }),
    );
    expect(parsed.brain?.lifecycle).toBe("per-task");
  });

  test("daemon still requires run when kind=exec", () => {
    expect(() =>
      AgentRuntimeSchema.parse(
        minRuntime({ kind: "exec", lifecycle: "daemon" }),
      ),
    ).toThrow(/brain\.run is required when brain\.kind is 'exec'/);
  });

  test("protocol pinned to cortex-brain/v1 — a wrong protocol fails", () => {
    expect(() =>
      AgentRuntimeSchema.parse(
        minRuntime({ kind: "exec", run: "bun x.ts", protocol: "cortex-brain/v2" }),
      ),
    ).toThrow();
  });

  test("maxRestarts must be a non-negative integer", () => {
    expect(() =>
      AgentRuntimeSchema.parse(minRuntime({ maxRestarts: -1 })),
    ).toThrow(/maxRestarts must be >= 0/);
    expect(() =>
      AgentRuntimeSchema.parse(minRuntime({ maxRestarts: 1.5 })),
    ).toThrow(/maxRestarts must be an integer/);
    // 0 is valid (no restarts).
    expect(
      AgentRuntimeSchema.parse(minRuntime({ maxRestarts: 0 })).brain?.maxRestarts,
    ).toBe(0);
  });

  test("builtin brain accepts an explicit kind without requiring run", () => {
    const parsed = AgentRuntimeSchema.parse(minRuntime({ kind: "builtin" }));
    expect(parsed.brain?.kind).toBe("builtin");
    expect(parsed.brain?.run).toBeUndefined();
  });
});

// =============================================================================
// Renderer schemas
// =============================================================================

describe("RendererSchema", () => {
  test("dashboard renderer parses with kind + defaults", () => {
    const parsed = DashboardRendererSchema.parse({ kind: "dashboard" });
    expect(parsed.port).toBe(8767);
    expect(parsed.subscribe).toEqual(["local.{principal}.>"]);
    expect(parsed.projections).toEqual([]);
  });

  test("pagerduty renderer requires routingKey", () => {
    expect(() => PagerDutyRendererSchema.parse({ kind: "pagerduty" })).toThrow();
    const parsed = PagerDutyRendererSchema.parse({
      kind: "pagerduty",
      routingKey: "PD-ROUTING-KEY",
      subscribe: ["local.{principal}.system.adapter.degraded"],
    });
    expect(parsed.routingKey).toBe("PD-ROUTING-KEY");
  });

  // cortex#1789 (S4, ADR-0024 D5) — `RendererSchema` stopped being a closed
  // discriminated union and became the loose STRUCTURAL pass
  // (`{kind: string, ...}`). Per-kind field validation (routingKey required,
  // url required, port/subscribe defaults, …) now lives ONLY on the
  // per-kind schemas above (`DashboardRendererSchema` etc, exercised
  // directly) and is enforced at the REGISTRY pass
  // (`resolveRendererPluginAndConfig`, `src/renderers/index.ts` —
  // `factory.test.ts` covers that dispatch). These tests pin the STRUCTURAL
  // schema's own, deliberately weaker, contract.
  test("structural pass preserves an arbitrary kind — no per-kind field enforcement", () => {
    const dashboard = RendererSchema.parse({ kind: "dashboard" });
    expect(dashboard.kind).toBe("dashboard");

    const cliTail = RendererSchema.parse({ kind: "cli-tail" });
    expect(cliTail.kind).toBe("cli-tail");
  });

  test("an out-of-tree kind is NOT rejected structurally — registry-contributed kinds must be admissible", () => {
    // Pre-S4 this threw (closed z.enum). It must NOT throw now: a
    // registry-contributed (post-S6) kind this static schema has never
    // heard of has to structurally parse so the REGISTRY pass — not this
    // schema — gets the chance to say "installed" or "not installed".
    expect(() => RendererSchema.parse({ kind: "telegram" })).not.toThrow();
  });

  test("kind is still required and must be a non-empty string", () => {
    expect(() => RendererSchema.parse({})).toThrow();
    expect(() => RendererSchema.parse({ kind: "" })).toThrow();
  });

  test("webhook-out renderer requires url", () => {
    expect(() => WebhookOutRendererSchema.parse({ kind: "webhook-out" })).toThrow();
    const parsed = WebhookOutRendererSchema.parse({
      kind: "webhook-out",
      url: "https://example.com/cortex-hook",
    });
    expect(parsed.kind).toBe("webhook-out");
  });

  test("webhook-out's missing url is NOT caught by the structural pass — only by the per-kind schema", () => {
    // Documents the deliberate gap: `RendererSchema` alone will happily
    // parse `{kind: "webhook-out"}` even though the real
    // `WebhookOutRendererSchema` requires `url`. This is why the registry
    // pass exists — see `resolveRendererPluginAndConfig`.
    const parsed = RendererSchema.parse({ kind: "webhook-out" });
    expect(parsed.kind).toBe("webhook-out");
    expect(() => WebhookOutRendererSchema.parse(parsed)).toThrow();
  });
});

// =============================================================================
// NATS schema
// =============================================================================

describe("NatsConfigSchema", () => {
  test("rejects http:// url", () => {
    expect(() => NatsConfigSchema.parse({ url: "http://localhost:4222" })).toThrow();
  });

  test("accepts nats:// url with defaults", () => {
    const parsed = NatsConfigSchema.parse({ url: "nats://localhost:4222" });
    expect(parsed.name).toBe("cortex");
    expect(parsed.subjects).toEqual([]);
  });

  test("accepts tls:// url", () => {
    const parsed = NatsConfigSchema.parse({ url: "tls://nats.example.com:4222" });
    expect(parsed.url).toBe("tls://nats.example.com:4222");
  });

  test("NatsIdentity rejects non-NKey publicKey", () => {
    expect(() => NatsIdentitySchema.parse({
      seedPath: "/etc/cortex/operator.nk",
      publicKey: "not-an-nkey",
    })).toThrow();
  });

  test("NatsIdentity rejects short NKey-shaped strings (Holly review)", () => {
    // Real NATS NKey user keys are exactly 56 chars (U + 55 base32). Short
    // placeholders like "U1" or "UABCDEF1234567890" must be rejected so a
    // typo at config time fails fast, not silently at NatsLink.connect.
    expect(() => NatsIdentitySchema.parse({
      seedPath: "/etc/cortex/operator.nk",
      publicKey: "U1",
    })).toThrow();
    expect(() => NatsIdentitySchema.parse({
      seedPath: "/etc/cortex/operator.nk",
      publicKey: "UABCDEF1234567890",
    })).toThrow();
  });

  test("NatsIdentity rejects lowercase / base32-incompatible chars", () => {
    // NKey base32 alphabet is A-Z 2-7 (RFC-4648). Lowercase, 0, 1, 8, 9 are
    // not in the alphabet; only the U prefix + 55 valid chars pass.
    const valid55 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567" + "ABCDEFGHIJKLMNOPQRSTUV"; // 32 + 22 = 54... need 55
    const full = "U" + (valid55 + "Z");
    expect(full).toHaveLength(56);
    const parsed = NatsIdentitySchema.parse({
      seedPath: "/etc/cortex/operator.nk",
      publicKey: full,
    });
    expect(parsed.publicKey).toBe(full);

    expect(() => NatsIdentitySchema.parse({
      seedPath: "/etc/cortex/operator.nk",
      publicKey: "U" + "abcdefghijklmnopqrstuvwxyz".padEnd(55, "A"),
    })).toThrow();
  });

  // C-108 (Prereq B for cortex#67): the account signing key path field is
  // optional, accepts a string path, and parses through unchanged. We don't
  // validate the path's contents at schema time — that's the loader's job
  // (`src/common/config/account-signing-key.ts`). Schema only carries the
  // shape; runtime owns the chmod + prefix gates.

  test("accountSigningKeyPath is optional (absent → undefined)", () => {
    const parsed = NatsConfigSchema.parse({ url: "nats://localhost:4222" });
    expect(parsed.accountSigningKeyPath).toBeUndefined();
  });

  test("accountSigningKeyPath accepts a string path", () => {
    const parsed = NatsConfigSchema.parse({
      url: "nats://localhost:4222",
      accountSigningKeyPath: "/etc/cortex/account-signing.nk",
    });
    expect(parsed.accountSigningKeyPath).toBe("/etc/cortex/account-signing.nk");
  });

  test("accountSigningKeyPath rejects non-string", () => {
    expect(() => NatsConfigSchema.parse({
      url: "nats://localhost:4222",
      accountSigningKeyPath: 42,
    })).toThrow();
  });

  // ─── credsPath (cortex#86) ─────────────────────────────────────────────
  // Path is just a string at the schema layer; chmod 600 + ~/ expansion +
  // file-read live in the NatsLink loader (`../bus/nats/connection.ts`).
  // Schema only carries shape so legacy + cortex config loaders agree.

  test("credsPath is optional (absent → undefined)", () => {
    const parsed = NatsConfigSchema.parse({ url: "nats://localhost:4222" });
    expect(parsed.credsPath).toBeUndefined();
  });

  test("credsPath accepts an absolute path", () => {
    const parsed = NatsConfigSchema.parse({
      url: "nats://localhost:4222",
      credsPath: "/etc/cortex/cortex.creds",
    });
    expect(parsed.credsPath).toBe("/etc/cortex/cortex.creds");
  });

  test("credsPath accepts a ~/ path (expansion happens in loader, not schema)", () => {
    const parsed = NatsConfigSchema.parse({
      url: "nats://localhost:4222",
      credsPath: "~/.config/nats/cortex.creds",
    });
    expect(parsed.credsPath).toBe("~/.config/nats/cortex.creds");
  });

  test("credsPath rejects non-string", () => {
    expect(() => NatsConfigSchema.parse({
      url: "nats://localhost:4222",
      credsPath: 42,
    })).toThrow();
  });
});

// =============================================================================
// AgentConfigSchema.nats.accountSigningKeyPath — MIRROR of cortex-config field
// =============================================================================
//
// We MIRROR the field across both schemas during the MIG-7.2 overlap window.
// Asserting the legacy schema accepts it (and round-trips it) protects against
// drift — if someone edits one schema and forgets the other, this test fails.

describe("AgentConfigSchema.nats.accountSigningKeyPath (MIRROR)", () => {
  /** Minimal AgentConfig shell to exercise the optional `nats` block. */
  function minAgentConfig(natsExtras: Record<string, unknown> = {}) {
    return {
      agent: { name: "test", displayName: "Test" },
      discord: [],
      mattermost: [],
      claude: { timeoutMs: 1000 },
      paths: { publishedEventsDir: "/tmp/x" },
      nats: {
        url: "nats://localhost:4222",
        ...natsExtras,
      },
    };
  }

  test("absent on legacy AgentConfig.nats → undefined", () => {
    const parsed = AgentConfigSchema.parse(minAgentConfig());
    expect(parsed.nats?.accountSigningKeyPath).toBeUndefined();
  });

  test("accepts a string path on legacy AgentConfig.nats", () => {
    const parsed = AgentConfigSchema.parse(
      minAgentConfig({ accountSigningKeyPath: "/etc/cortex/account-signing.nk" }),
    );
    expect(parsed.nats?.accountSigningKeyPath).toBe("/etc/cortex/account-signing.nk");
  });

  test("credsPath (cortex#86) mirrors onto AgentConfig.nats", () => {
    const parsed = AgentConfigSchema.parse(
      minAgentConfig({ credsPath: "~/.config/nats/cortex.creds" }),
    );
    expect(parsed.nats?.credsPath).toBe("~/.config/nats/cortex.creds");
  });

  test("credsPath rejects non-string on legacy AgentConfig.nats", () => {
    expect(() =>
      AgentConfigSchema.parse(minAgentConfig({ credsPath: 42 })),
    ).toThrow();
  });

  test("rejects non-string on legacy AgentConfig.nats", () => {
    expect(() => AgentConfigSchema.parse(
      minAgentConfig({ accountSigningKeyPath: 42 }),
    )).toThrow();
  });
});

describe("AgentConfigSchema.mc (MC-I1.S1)", () => {
  /** Minimal AgentConfig shell; `mc` override is spread in when provided. */
  function minAgentConfig(mc?: Record<string, unknown>) {
    return {
      agent: { name: "test", displayName: "Test" },
      discord: [],
      mattermost: [],
      claude: { timeoutMs: 1000 },
      paths: { publishedEventsDir: "/tmp/x" },
      ...(mc !== undefined && { mc }),
    };
  }

  test("absent mc block → enabled false, all fields populated by the transform", () => {
    // The `.default(emptyDefault())` quirk: without the transform re-applying
    // inner defaults, these fields would be undefined. Assert the populated shape.
    const parsed = AgentConfigSchema.parse(minAgentConfig());
    expect(parsed.mc).toEqual({
      enabled: false,
      configPath: "",
      dbPath: "",
      port: 0,
      // P-14 U0.1 — sideband defaults to the contract loopback bind.
      sideband: "http://127.0.0.1:9092",
      // #1044 — the HTTP server defaults ON (full MC); headless sets it false.
      server: { enabled: true },
      // #989 — local-stack aggregation defaults ON; discovery is a no-op on a
      // single-stack box (finds no siblings).
      // #1008 — dbRead pane-of-glass aggregation defaults ON alongside `enabled`.
      aggregateLocalStacks: { enabled: true, dbRead: true, configRoot: "", stacks: [] },
    });
  });

  test("empty mc block ({}) → same populated defaults", () => {
    const parsed = AgentConfigSchema.parse(minAgentConfig({}));
    expect(parsed.mc.enabled).toBe(false);
    expect(parsed.mc.configPath).toBe("");
    expect(parsed.mc.dbPath).toBe("");
    expect(parsed.mc.port).toBe(0);
  });

  test("explicit values are honored", () => {
    const parsed = AgentConfigSchema.parse(
      minAgentConfig({
        enabled: true,
        configPath: "~/.config/cortex/mc.yaml",
        dbPath: "~/.local/share/cortex/mc/meta-factory/mission-control.db",
        port: 8767,
      }),
    );
    expect(parsed.mc.enabled).toBe(true);
    expect(parsed.mc.configPath).toBe("~/.config/cortex/mc.yaml");
    expect(parsed.mc.dbPath).toBe("~/.local/share/cortex/mc/meta-factory/mission-control.db");
    expect(parsed.mc.port).toBe(8767);
  });

  test("partial mc block fills the rest from defaults", () => {
    const parsed = AgentConfigSchema.parse(minAgentConfig({ enabled: true }));
    expect(parsed.mc.enabled).toBe(true);
    expect(parsed.mc.configPath).toBe("");
    expect(parsed.mc.dbPath).toBe("");
    expect(parsed.mc.port).toBe(0);
  });

  test("port rejects a negative value (nonnegative int)", () => {
    expect(() => AgentConfigSchema.parse(minAgentConfig({ port: -1 }))).toThrow();
  });

  test("port rejects a non-integer value", () => {
    expect(() => AgentConfigSchema.parse(minAgentConfig({ port: 8767.5 }))).toThrow();
  });
});

// =============================================================================
// P-14 U0.1 — mc.sideband loopback enforcement + shared-schema parity
// (signal cortex-sideband.md §3/§8; the #877/#879 shared-McSchema lesson)
// =============================================================================

describe("mc.sideband (P-14 U0.1)", () => {
  /** Minimal AgentConfig shell with an mc override. */
  function minAgentConfig(mc?: Record<string, unknown>) {
    return {
      agent: { name: "test", displayName: "Test" },
      discord: [],
      mattermost: [],
      claude: { timeoutMs: 1000 },
      paths: { publishedEventsDir: "/tmp/x" },
      ...(mc !== undefined && { mc }),
    };
  }

  test("absent mc block → sideband defaults to the contract loopback bind", () => {
    const parsed = AgentConfigSchema.parse(minAgentConfig());
    expect(parsed.mc.sideband).toBe("http://127.0.0.1:9092");
  });

  test("empty mc block ({}) → sideband default", () => {
    const parsed = AgentConfigSchema.parse(minAgentConfig({}));
    expect(parsed.mc.sideband).toBe("http://127.0.0.1:9092");
  });

  test("accepts an explicit loopback override (custom port / localhost / IPv6)", () => {
    for (const sideband of [
      "http://127.0.0.1:19092",
      "http://localhost:9092",
      "http://[::1]:9092",
    ]) {
      const parsed = AgentConfigSchema.parse(minAgentConfig({ sideband }));
      expect(parsed.mc.sideband).toBe(sideband);
    }
  });

  test("REJECTS a non-loopback sideband (fail-closed, §8)", () => {
    for (const sideband of [
      "http://0.0.0.0:9092",
      "http://192.168.1.5:9092",
      "http://10.0.0.9:9092",
      "http://sideband.evil.com:9092",
      "ws://127.0.0.1:9092",
    ]) {
      expect(() => AgentConfigSchema.parse(minAgentConfig({ sideband }))).toThrow(/mc\.sideband/);
    }
  });

  // ---- Shared-schema parity: BOTH config schemas must see mc.sideband ----
  // The #877/#879 lesson: any new mc.* key MUST live on the SHARED McSchema so
  // AgentConfigSchema (legacy bot.yaml) AND CortexConfigSchema (config-split)
  // both parse it. A field defined on only one schema gets silently stripped
  // for the other shape's deployments.

  describe("shared-schema parity", () => {
    test("CortexConfigSchema parses mc.sideband (default)", () => {
      const parsed = CortexConfigSchema.parse(minConfig());
      expect(parsed.mc.sideband).toBe("http://127.0.0.1:9092");
    });

    test("CortexConfigSchema accepts a loopback override", () => {
      const parsed = CortexConfigSchema.parse({
        ...minConfig(),
        mc: { enabled: true, sideband: "http://localhost:19092" },
      });
      expect(parsed.mc.sideband).toBe("http://localhost:19092");
    });

    test("CortexConfigSchema REJECTS a non-loopback sideband (parity with AgentConfigSchema)", () => {
      expect(() =>
        CortexConfigSchema.parse({
          ...minConfig(),
          mc: { enabled: true, sideband: "http://192.168.1.5:9092" },
        }),
      ).toThrow(/mc\.sideband/);
    });

    test("BOTH schemas reject the SAME non-loopback value and accept the SAME loopback value", () => {
      const bad = "http://0.0.0.0:9092";
      const good = "http://127.0.0.2:9092";
      // Agent shape
      expect(() => AgentConfigSchema.parse(minAgentConfig({ sideband: bad }))).toThrow();
      expect(AgentConfigSchema.parse(minAgentConfig({ sideband: good })).mc.sideband).toBe(good);
      // Cortex shape
      expect(() =>
        CortexConfigSchema.parse({ ...minConfig(), mc: { sideband: bad } }),
      ).toThrow();
      expect(
        CortexConfigSchema.parse({ ...minConfig(), mc: { sideband: good } }).mc.sideband,
      ).toBe(good);
    });

    // #989 — mc.aggregateLocalStacks is on the SHARED McSchema, so BOTH config
    // shapes must parse it identically (the #877/#879 lesson).
    test("BOTH schemas default mc.aggregateLocalStacks ON with empty roster", () => {
      const fromAgent = AgentConfigSchema.parse(minAgentConfig()).mc
        .aggregateLocalStacks;
      const fromCortex = CortexConfigSchema.parse(minConfig()).mc
        .aggregateLocalStacks;
      const expected = { enabled: true, dbRead: true, configRoot: "", stacks: [] };
      expect(fromAgent).toEqual(expected);
      expect(fromCortex).toEqual(expected);
    });

    test("BOTH schemas parse an explicit aggregateLocalStacks roster identically", () => {
      const block = {
        enabled: true,
        dbRead: true,
        configRoot: "~/.config/cortex",
        stacks: [
          {
            stack: "work",
            principal: "andreas",
            url: "nats://127.0.0.1:4222",
            credsPath: "~/.config/nats/cortex-work.creds",
          },
        ],
      };
      const agentParsed = AgentConfigSchema.parse({
        ...minAgentConfig(),
        mc: { aggregateLocalStacks: block },
      }).mc.aggregateLocalStacks;
      const cortexParsed = CortexConfigSchema.parse({
        ...minConfig(),
        mc: { aggregateLocalStacks: block },
      }).mc.aggregateLocalStacks;
      expect(agentParsed).toEqual(block);
      expect(cortexParsed).toEqual(block);
    });

    // #1044 — mc.server.enabled is on the SHARED McSchema (headless MC mode:
    // run db+ingestor, skip the HTTP server). BOTH config shapes must parse it
    // identically (the #877/#879 lesson) or a headless work/halden stack on the
    // config-split shape would silently keep its server flag stripped.
    test("BOTH schemas default mc.server.enabled to true (full mode)", () => {
      const fromAgent = AgentConfigSchema.parse(minAgentConfig()).mc.server;
      const fromCortex = CortexConfigSchema.parse(minConfig()).mc.server;
      const expected = { enabled: true };
      expect(fromAgent).toEqual(expected);
      expect(fromCortex).toEqual(expected);
    });

    test("BOTH schemas parse an explicit mc.server.enabled:false (headless) identically", () => {
      const fromAgent = AgentConfigSchema.parse(
        minAgentConfig({ server: { enabled: false } }),
      ).mc.server;
      const fromCortex = CortexConfigSchema.parse({
        ...minConfig(),
        mc: { server: { enabled: false } },
      }).mc.server;
      const expected = { enabled: false };
      expect(fromAgent).toEqual(expected);
      expect(fromCortex).toEqual(expected);
    });

    test("empty mc block ({}) → server.enabled defaults true on BOTH schemas", () => {
      expect(AgentConfigSchema.parse(minAgentConfig({})).mc.server.enabled).toBe(true);
      expect(
        CortexConfigSchema.parse({ ...minConfig(), mc: {} }).mc.server.enabled,
      ).toBe(true);
    });
  });
});

// =============================================================================
// Renderer URL validation
// =============================================================================

describe("DashboardRendererSchema.publicUrl", () => {
  test("accepts a valid https URL", () => {
    const parsed = DashboardRendererSchema.parse({
      kind: "dashboard",
      publicUrl: "https://cortex.meta-factory.ai",
    });
    expect(parsed.publicUrl).toBe("https://cortex.meta-factory.ai");
  });

  test("rejects a non-URL string", () => {
    expect(() => DashboardRendererSchema.parse({
      kind: "dashboard",
      publicUrl: "not a url",
    })).toThrow();
  });
});

describe("WebhookOutRenderer.url", () => {
  test("rejects a non-URL string", () => {
    // cortex#1789 (S4) — `RendererSchema` (the structural pass) no longer
    // validates `url`'s format; that's `WebhookOutRendererSchema`'s job now
    // (the registry pass's per-kind schema — see `resolveRendererPluginAndConfig`).
    expect(() => WebhookOutRendererSchema.parse({
      kind: "webhook-out",
      url: "not-a-url",
    })).toThrow();
  });
});

// =============================================================================
// Cross-cutting schemas — minimal standalone tests
// =============================================================================

describe("Cross-cutting schemas — defaults populated by emptyDefault helper", () => {
  test("ClaudeConfigSchema applies inner defaults", () => {
    const parsed = ClaudeConfigSchema.parse({});
    expect(parsed.timeoutMs).toBe(120_000);
    expect(parsed.asyncTimeoutMs).toBe(900_000);
    expect(parsed.allowedTools).toEqual([]);
    expect(parsed.allowedDirs).toEqual([]);
  });

  test("AttachmentsConfigSchema applies inner defaults", () => {
    const parsed = AttachmentsConfigSchema.parse({});
    expect(parsed.enabled).toBe(true);
    expect(parsed.maxFileSizeBytes).toBe(10 * 1024 * 1024);
  });

  test("ExecutionConfigSchema applies inner defaults", () => {
    const parsed = ExecutionConfigSchema.parse({});
    expect(parsed.default).toBe("local");
    expect(parsed.backends).toEqual([]);
  });

  test("GithubConfigSchema applies inner defaults via emptyDefault for agentDetection", () => {
    const parsed = GithubConfigSchema.parse({});
    expect(parsed.webhookSecret).toBe("");
    expect(parsed.repos).toEqual([]);
    expect(parsed.agentDetection.commitTrailers).toEqual(["Co-Authored-By: Claude"]);
  });

  test("PathsConfigSchema applies inner defaults", () => {
    const parsed = PathsConfigSchema.parse({});
    // XDG wave-5 (#1902): published-events buffer moved under the metafactory data root.
    expect(parsed.publishedEventsDir).toBe(
      "~/.local/share/metafactory/cortex/events/published",
    );
    // XDG wave-5 (#1903): logs are STATE — moved under the metafactory state root.
    expect(parsed.logDir).toBe("~/.local/state/metafactory/cortex/logs");
  });

  test("AgentDetectionSchema applies inner defaults", () => {
    const parsed = AgentDetectionSchema.parse({});
    expect(parsed.branchPatterns).toEqual(["^feat/(g|f|i)-\\d+"]);
    expect(parsed.commentPatterns).toEqual(["^Starting:", "^Completed:"]);
  });

  test("BusConfigSchema applies review + lifecycle + devImplement stream defaults (cortex#835, F-2.2)", () => {
    const parsed = BusConfigSchema.parse({});
    // Existing CODE_REVIEW posture — unchanged.
    expect(parsed.review.stream.name).toBe("CODE_REVIEW");
    expect(parsed.review.stream.maxAgeSeconds).toBe(86_400);
    expect(parsed.review.stream.maxBytes).toBe(64 * 1024 * 1024);
    expect(parsed.review.consumer.maxDeliver).toBe(5);
    // New REVIEW_LIFECYCLE stream — mirrors CODE_REVIEW's stream posture
    // exactly, and intentionally carries NO consumer sub-block (cortex
    // provisions the stream; the durable consumers are the downstream
    // reactor's concern — the cortex#835 follow-up).
    expect(parsed.lifecycle.stream.name).toBe("REVIEW_LIFECYCLE");
    expect(parsed.lifecycle.stream.maxAgeSeconds).toBe(86_400);
    expect(parsed.lifecycle.stream.maxBytes).toBe(64 * 1024 * 1024);
    expect("consumer" in parsed.lifecycle).toBe(false);
    // The two stream names MUST differ — they own disjoint subject spaces,
    // and a shared name would clash on `streams.add`.
    expect(parsed.lifecycle.stream.name).not.toBe(parsed.review.stream.name);
    // New DEV_IMPLEMENT stream — mirrors CODE_REVIEW's stream posture exactly,
    // and intentionally carries NO consumer sub-block (cortex provisions the
    // stream; the dev-agent's durable consumer is F-2.1's concern, cortex#853).
    expect(parsed.devImplement.stream.name).toBe("DEV_IMPLEMENT");
    expect(parsed.devImplement.stream.maxAgeSeconds).toBe(86_400);
    expect(parsed.devImplement.stream.maxBytes).toBe(64 * 1024 * 1024);
    expect("consumer" in parsed.devImplement).toBe(false);
    // The DEV_IMPLEMENT name MUST differ from BOTH siblings — they own disjoint
    // subject spaces, and a shared name would clash on `streams.add`.
    expect(parsed.devImplement.stream.name).not.toBe(parsed.review.stream.name);
    expect(parsed.devImplement.stream.name).not.toBe(parsed.lifecycle.stream.name);
  });

  test("BusConfigSchema honors explicit lifecycle overrides", () => {
    const parsed = BusConfigSchema.parse({
      lifecycle: { stream: { name: "MY_LIFECYCLE", maxAgeSeconds: 3600, maxBytes: 1024 } },
    });
    expect(parsed.lifecycle.stream.name).toBe("MY_LIFECYCLE");
    expect(parsed.lifecycle.stream.maxAgeSeconds).toBe(3600);
    expect(parsed.lifecycle.stream.maxBytes).toBe(1024);
  });

  test("BusConfigSchema rejects non-positive lifecycle stream limits", () => {
    expect(() =>
      BusConfigSchema.parse({ lifecycle: { stream: { maxAgeSeconds: 0 } } }),
    ).toThrow();
    expect(() =>
      BusConfigSchema.parse({ lifecycle: { stream: { maxBytes: -1 } } }),
    ).toThrow();
  });

  test("BusDevImplementConfigSchema honors explicit overrides", () => {
    const parsed = BusDevImplementConfigSchema.parse({
      stream: { name: "MY_DEV", maxAgeSeconds: 3600, maxBytes: 1024 },
    });
    expect(parsed.stream.name).toBe("MY_DEV");
    expect(parsed.stream.maxAgeSeconds).toBe(3600);
    expect(parsed.stream.maxBytes).toBe(1024);
  });

  test("BusDevImplementConfigSchema rejects non-positive stream limits", () => {
    expect(() =>
      BusDevImplementConfigSchema.parse({ stream: { maxAgeSeconds: 0 } }),
    ).toThrow();
    expect(() =>
      BusDevImplementConfigSchema.parse({ stream: { maxBytes: -1 } }),
    ).toThrow();
    expect(() =>
      BusDevImplementConfigSchema.parse({ stream: { name: "" } }),
    ).toThrow();
  });
});

// =============================================================================
// CortexConfig — top-level invariants
// =============================================================================

describe("CortexConfigSchema", () => {
  test("accepts minimal valid config", () => {
    const parsed = CortexConfigSchema.parse(minConfig());
    expect(parsed.principal.id).toBe("andreas");
    expect(parsed.agents).toHaveLength(1);
    expect(parsed.renderers).toEqual([]);
  });

  test("rejects empty agents[]", () => {
    expect(() => CortexConfigSchema.parse({
      ...minConfig(),
      agents: [],
    })).toThrow(/at least one agent/);
  });

  test("rejects duplicate agent ids", () => {
    expect(() => CortexConfigSchema.parse({
      ...minConfig(),
      agents: [minAgent({ id: "luna" }), minAgent({ id: "luna" })],
    })).toThrow(/agent ids must be unique/);
  });

  test("accepts full multi-agent + renderers + nats config", () => {
    const parsed = CortexConfigSchema.parse({
      principal: {
        id: "andreas",
        displayName: "Andreas Astrom",
        discordId: "5555555555555555555",
      },
      agents: [
        minAgent({ id: "luna", roles: ["operator"], trust: ["echo", "holly"] }),
        minAgent({ id: "echo", roles: ["agent-restricted"], trust: ["luna", "holly"] }),
        minAgent({ id: "holly", roles: ["agent-restricted"], trust: ["luna"] }),
      ],
      renderers: [
        { kind: "dashboard", port: 8767, publicUrl: "https://cortex.meta-factory.ai" },
        { kind: "pagerduty", routingKey: "PD-KEY", subscribe: ["local.{principal}.system.>"] },
      ],
      claude: {},
      nats: {
        url: "nats://localhost:4222",
        subjects: ["local.{principal}.>"],
        identity: {
          seedPath: "/etc/cortex/andreas.nk",
          publicKey: VALID_NKEY,
        },
      },
    });

    expect(parsed.agents).toHaveLength(3);
    expect(parsed.renderers).toHaveLength(2);
    expect(parsed.nats?.identity?.publicKey).toBe(VALID_NKEY);

    const dashboard = parsed.renderers.find((r) => r.kind === "dashboard");
    expect(dashboard?.kind === "dashboard" && dashboard.publicUrl).toBe(
      "https://cortex.meta-factory.ai",
    );
  });

  test("trust list is preserved verbatim (no resolution at schema layer)", () => {
    // Coupling rule §9.3: schema accepts trust as strings; the agent registry
    // (MIG-7.2a) validates that the referenced ids exist. Schema must not
    // pre-empt that responsibility.
    const parsed = CortexConfigSchema.parse({
      ...minConfig(),
      agents: [minAgent({ trust: ["echo", "ghost-agent-that-doesnt-exist"] })],
    });
    expect(parsed.agents[0]?.trust).toEqual(["echo", "ghost-agent-that-doesnt-exist"]);
  });

  // CO-1 (epic cortex#939) — cross-block: an offered capability must EXIST in
  // the stack's declared capabilities[]. This check lives on CortexConfigSchema
  // (not PolicySchema) because it needs the top-level capabilities[] catalog.
  test("CO-1: byte-identical — minConfig (no offerings) parses with policy absent", () => {
    const parsed = CortexConfigSchema.parse(minConfig());
    // No policy block ⇒ no offerings ⇒ every capability resolves local-only.
    expect(parsed.policy).toBeUndefined();
  });

  test("CO-1: a config WITH a declared+provided capability may offer it", () => {
    const parsed = CortexConfigSchema.parse({
      ...minConfig(),
      capabilities: [
        {
          id: "code-review.typescript",
          description: "Reviews TypeScript PRs",
          provided_by: ["luna"],
        },
      ],
      // CO-7 M3: a `public` offering requires a non-local execution backend
      // (the fail-closed gate below), so this happy-path config declares one.
      execution: {
        default: "cf-sandbox",
        backends: [{ name: "cf-sandbox", type: "cloudflare", endpoint: "https://sb" }],
      },
      policy: {
        offerings: [
          {
            capability: "code-review.typescript",
            scopes: ["public"],
            accept: {
              kind: "surface",
              surface: "github",
              predicate: { kind: "repo-membership", repos: ["the-metafactory/*"] },
            },
          },
        ],
      },
    });
    expect(parsed.policy?.offerings).toHaveLength(1);
  });

  // CO-7 M3 (epic cortex#939) — the public-offering ⇒ non-local-backend
  // FAIL-CLOSED gate. A `public` offering on a local (or unset) execution
  // backend is REJECTED at config-validation so untrusted PR code never runs
  // on the principal's host (design §6 M3, ADR-0008 DD-CO-6). The backend
  // itself is deferred infra (cortex#978); CO-7 ships the prevent-side gate.
  test("CO-7 M3: REJECTS a public offering on the default (local) backend", () => {
    expect(() =>
      CortexConfigSchema.parse({
        ...minConfig(),
        capabilities: [
          {
            id: "code-review.typescript",
            description: "Reviews TypeScript PRs",
            provided_by: ["luna"],
          },
        ],
        // execution omitted ⇒ default `local`.
        policy: {
          offerings: [
            {
              capability: "code-review.typescript",
              scopes: ["public"],
              accept: {
                kind: "surface",
                surface: "github",
                predicate: { kind: "repo-membership", repos: ["the-metafactory/*"] },
              },
            },
          ],
        },
      }),
    ).toThrow(/non-local ExecutionBackend/);
  });

  test("CO-7 M3: a LOCAL/FEDERATED offering is NOT gated by the backend rule", () => {
    // A federated offering on a local backend is fine — the M3 gate is public-only.
    const parsed = CortexConfigSchema.parse({
      ...minConfig(),
      capabilities: [
        { id: "chat", description: "chat", provided_by: ["luna"] },
      ],
      policy: {
        offerings: [
          {
            capability: "chat",
            scopes: ["federated"],
            accept: { kind: "network", network: "mf-net" },
          },
        ],
      },
    });
    expect(parsed.policy?.offerings).toHaveLength(1);
  });

  test("CO-7 M3: a public offering on a NON-LOCAL backend passes the gate", () => {
    const parsed = CortexConfigSchema.parse({
      ...minConfig(),
      capabilities: [
        {
          id: "code-review.typescript",
          description: "Reviews TypeScript PRs",
          provided_by: ["luna"],
        },
      ],
      execution: {
        default: "e2b-sandbox",
        backends: [{ name: "e2b-sandbox", type: "e2b", endpoint: "https://e2b" }],
      },
      policy: {
        offerings: [
          {
            capability: "code-review.typescript",
            scopes: ["public"],
            accept: {
              kind: "surface",
              surface: "github",
              predicate: { kind: "repo-membership", repos: ["the-metafactory/*"] },
            },
          },
        ],
      },
    });
    expect(parsed.policy?.offerings).toHaveLength(1);
  });

  test("CO-1: REJECTS offering a capability the stack does not declare", () => {
    expect(() =>
      CortexConfigSchema.parse({
        ...minConfig(),
        // capabilities[] omitted ⇒ catalog is empty
        policy: {
          offerings: [{ capability: "phantom.capability", scopes: ["local"] }],
        },
      }),
    ).toThrow(/no matching entry exists in the top-level capabilities\[\] catalog/);
  });

  test("defaults are applied for optional top-level blocks (Holly W2 — emptyDefault closes Zod quirk)", () => {
    // Before MIG-7.2 rev 2: outer `.default({} as any)` did NOT re-parse the
    // default through the inner schema, so omitting `attachments` gave `{}`
    // literally instead of `{ enabled: true, ... }`. The `emptyDefault`
    // helper computes the inner-default-applied shape at load time and uses
    // it as the literal default, so omitting the field now produces the
    // populated shape that downstream code expects.
    const parsed = CortexConfigSchema.parse(minConfig());
    expect(parsed.attachments.enabled).toBe(true);
    expect(parsed.attachments.maxFileSizeBytes).toBe(10 * 1024 * 1024);
    expect(parsed.execution.default).toBe("local");
    expect(parsed.github.webhookSecret).toBe("");
    expect(parsed.github.agentDetection.commitTrailers).toEqual(["Co-Authored-By: Claude"]);
    expect(parsed.paths.publishedEventsDir).toBe(
      "~/.local/share/metafactory/cortex/events/published",
    );
    // XDG wave-5 (#1903): logs are STATE — moved under the metafactory state root.
    expect(parsed.paths.logDir).toBe("~/.local/state/metafactory/cortex/logs");
    expect(parsed.networksDir).toBe("./networks");
  });

  test("rejects legacy `agent:` (singular) field with a migration error (Holly W2-1)", () => {
    // The new schema has no `agent:` block (that's grove-v2's shape). Round-1
    // relied on Zod's silent unknown-key strip; round-2 flags this as a real
    // migration safety gap — principals who hand-edit a partial cortex.yaml
    // get no feedback that the legacy field is being ignored.
    //
    // Fix: the `agent` slot is now `z.never()` with an explicit error pointing
    // at `migrate-config` (MIG-7.2e). A config carrying both `agent:{}` and
    // `agents:[]` fails at parse time with a clear migration error.
    expect(() => CortexConfigSchema.parse({
      ...minConfig(),
      agent: { name: "luna", displayName: "Luna" },
    })).toThrow(/legacy `agent:`/);
  });

  test("rejects legacy `trustedAgentBots:` field with a migration error (Holly W2-1)", () => {
    // Same migration-safety rationale as the `agent:` anti-field — legacy
    // grove-v2 had a top-level `trustedAgentBots:` block that's now expressed
    // per-agent as `trust:[]`. The schema rejects the legacy shape so a
    // hand-migration miss surfaces at config load.
    expect(() => CortexConfigSchema.parse({
      ...minConfig(),
      trustedAgentBots: ["echo", "holly"],
    })).toThrow(/legacy `trustedAgentBots:`/);
  });

  test("rejects legacy top-level `discord:` array with a migration error (Holly W3)", () => {
    // Top-level `discord:[]` was the grove-v2 sibling of `agent:`. In cortex,
    // per-instance credentials live under `agents[<id>].presence.discord`.
    // Without this guard, a hand-migration miss strips the legacy block
    // silently and the principal gets a headless agent without an obvious
    // migration signal (cortex#245 removed the per-agent "at least one
    // presence" refine, so headless is no longer a useful proxy alert).
    expect(() => CortexConfigSchema.parse({
      ...minConfig(),
      discord: [{ token: "x", guildId: "1", agentChannelId: "2", logChannelId: "3" }],
    })).toThrow(/legacy top-level `discord:`/);
    expect(() => CortexConfigSchema.parse({
      ...minConfig(),
      discord: [{ token: "x", guildId: "1", agentChannelId: "2", logChannelId: "3" }],
    })).toThrow(/agents\[<id>\]\.presence\.discord/);
  });

  test("rejects legacy top-level `mattermost:` array with a migration error (Holly W3)", () => {
    // Same migration-safety rationale as the `discord:` anti-field above.
    expect(() => CortexConfigSchema.parse({
      ...minConfig(),
      mattermost: [{ apiUrl: "https://mm.example.com", apiToken: "tok" }],
    })).toThrow(/legacy top-level `mattermost:`/);
    expect(() => CortexConfigSchema.parse({
      ...minConfig(),
      mattermost: [{ apiUrl: "https://mm.example.com", apiToken: "tok" }],
    })).toThrow(/agents\[<id>\]\.presence\.mattermost/);
  });
});

// =============================================================================
// MIRROR sync — cortex cross-cutting schemas vs AgentConfigSchema
// =============================================================================
//
// Six cortex schemas (Claude / Attachments / Execution / Github + AgentDetection
// / Paths) carry MIRROR breadcrumbs in their JSDoc pointing at the corresponding
// AgentConfigSchema block. The breadcrumb is a manual guard during the MIG-7.2
// overlap window — a field added on one side must be added on the other side
// too, otherwise downstream code that reads AgentConfig and writes CortexConfig
// (or vice versa) silently drops data. These tests are the structural check
// that fires automatically if the breadcrumbs are missed.
//
// Method: parse `{}` on each cortex schema, parse the minimum AgentConfig
// (which applies inner defaults to optional cross-cutting blocks), and compare.
// Default-value equality is the strictest test because it catches both field
// additions/removals AND default drift. The former `paths.logDir` divergence
// (grove vs cortex namespace) is RESOLVED as of XDG wave-5 (#1903) — logs became
// STATE and both defaults now point at the shared metafactory state root — so
// `paths` mirrors fully (key-set match plus per-field equality).

describe("PolicyFederatedRegistrySchema — IAW D.4.3", () => {
  test("accepts a fully populated registry block (url + pubkey)", () => {
    const r = PolicyFederatedRegistrySchema.parse({
      url: "https://network.meta-factory.ai",
      // 43-char base64 alphabet + "=" padding → 44 chars total. The
      // value here is structural only; signature paths exercise real
      // keys at the client test layer.
      pubkey: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
    });
    expect(r.url).toBe("https://network.meta-factory.ai");
    expect(r.pubkey).toBe("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=");
  });

  test("accepts a url-only block (TOFU posture)", () => {
    const r = PolicyFederatedRegistrySchema.parse({
      url: "https://network.meta-factory.ai/",
    });
    expect(r.pubkey).toBeUndefined();
  });

  test("rejects a malformed url", () => {
    expect(() =>
      PolicyFederatedRegistrySchema.parse({ url: "not-a-url" }),
    ).toThrow();
  });

  test("rejects a pubkey that isn't base64 of the right length", () => {
    expect(() =>
      PolicyFederatedRegistrySchema.parse({
        url: "https://network.meta-factory.ai",
        pubkey: "tooshort",
      }),
    ).toThrow();
  });

  test("PolicyFederatedSchema accepts an optional registry sub-block", () => {
    // Absence is allowed (no registry → no consultation).
    const without = PolicyFederatedSchema.parse({});
    expect(without.registry).toBeUndefined();
    expect(without.networks).toEqual([]);

    // Presence parses through and round-trips.
    const withReg = PolicyFederatedSchema.parse({
      networks: [],
      registry: { url: "https://network.meta-factory.ai" },
    });
    expect(withReg.registry?.url).toBe("https://network.meta-factory.ai");
  });
});

describe("PolicyPublicSchema — IAW S5 (#739) public-scope opt-in (OQ1 safe default)", () => {
  test("defaults are deny-by-default: enabled=false, empty allowlist", () => {
    const parsed = PolicyPublicSchema.parse({});
    expect(parsed.enabled).toBe(false);
    expect(parsed.allow_principals).toEqual([]);
    expect(parsed.announce_capabilities).toEqual([]);
  });

  test("there is NO open-claim / anonymous knob (strict — rejects extra keys)", () => {
    // The safe-default contract: a config CANNOT express 'open anonymous claim'.
    // .strict() rejects an attempt to add one, so the abuse story stays deferred.
    expect(() =>
      PolicyPublicSchema.parse({ enabled: true, open_claim: true }),
    ).toThrow();
    expect(() =>
      PolicyPublicSchema.parse({ enabled: true, anonymous: true }),
    ).toThrow();
  });

  test("accepts an explicit allowlist (the only way to admit a public sender)", () => {
    const parsed = PolicyPublicSchema.parse({
      enabled: true,
      allow_principals: ["jc", "joel"],
      announce_capabilities: ["code-review.typescript"],
    });
    expect(parsed.enabled).toBe(true);
    expect(parsed.allow_principals).toEqual(["jc", "joel"]);
    expect(parsed.announce_capabilities).toEqual(["code-review.typescript"]);
  });

  test("rejects a malformed allow_principals id", () => {
    expect(() =>
      PolicyPublicSchema.parse({ enabled: true, allow_principals: ["BAD_ID"] }),
    ).toThrow();
  });

  test("rejects a malformed announce_capabilities id (must be <domain>.<entity>)", () => {
    expect(() =>
      PolicyPublicSchema.parse({ announce_capabilities: ["nodot"] }),
    ).toThrow();
  });
});

describe("PolicySchema — CO-1 offerings (epic cortex#939)", () => {
  test("defaults: offerings is absent (undefined) ⇒ default-deny baseline (byte-identical)", () => {
    // Mirrors the sibling federated/public widening blocks: absent, not [].
    // `resolveOffering(undefined)` is the single source of default-deny.
    const parsed = PolicySchema.parse({});
    expect(parsed.offerings).toBeUndefined();
  });

  test("accepts a valid local-only offering", () => {
    const parsed = PolicySchema.parse({
      offerings: [{ capability: "chat", scopes: ["local"] }],
    });
    expect(parsed.offerings).toHaveLength(1);
    expect(parsed.offerings?.[0]?.capability).toBe("chat");
  });

  test("accepts a federated offering with a named network accept", () => {
    const parsed = PolicySchema.parse({
      offerings: [
        {
          capability: "chat",
          scopes: ["federated"],
          accept: { kind: "network", network: "mf-net" },
        },
      ],
    });
    expect(parsed.offerings?.[0]?.accept?.kind).toBe("network");
  });

  test("accepts a public offering with a metadata-only surface accept", () => {
    const parsed = PolicySchema.parse({
      offerings: [
        {
          capability: "code-review.typescript",
          scopes: ["public"],
          accept: {
            kind: "surface",
            surface: "github",
            predicate: { kind: "repo-membership", repos: ["the-metafactory/*"] },
            limits: { per_day: 100 },
          },
        },
      ],
    });
    expect(parsed.offerings?.[0]?.accept?.kind).toBe("surface");
  });

  test("REJECTS a federated offering with no accept (default-deny)", () => {
    expect(() =>
      PolicySchema.parse({
        offerings: [{ capability: "chat", scopes: ["federated"] }],
      }),
    ).toThrow(/DEFAULT-DENY/);
  });

  test("REJECTS a public offering with a content-dependent predicate", () => {
    expect(() =>
      PolicySchema.parse({
        offerings: [
          {
            capability: "code-review.typescript",
            scopes: ["public"],
            accept: {
              kind: "surface",
              surface: "github",
              // content-dependent predicate — no such `kind` in the closed set
              predicate: { kind: "description-contains", value: "review me" },
            },
          },
        ],
      }),
    ).toThrow();
  });

  test("REJECTS duplicate capability offerings", () => {
    expect(() =>
      PolicySchema.parse({
        offerings: [
          { capability: "chat", scopes: ["local"] },
          { capability: "chat", scopes: ["local"] },
        ],
      }),
    ).toThrow(/already declared at offerings\[0\]/);
  });

  test("REJECTS a local-only offering carrying an accept", () => {
    expect(() =>
      PolicySchema.parse({
        offerings: [
          {
            capability: "chat",
            scopes: ["local"],
            accept: { kind: "network", network: "mf-net" },
          },
        ],
      }),
    ).toThrow(/local-only but carries an accept-policy/);
  });
});

describe("MIRROR sync — cortex cross-cutting schemas vs AgentConfigSchema", () => {
  // Minimum AgentConfig that exposes inner defaults on every cross-cutting block.
  //
  // AgentConfig pre-dates the cortex-side `emptyDefault` helper, so its outer
  // `.default({} as any)` wrappers exhibit the Zod v4 quirk documented on
  // `emptyDefault`: omitting the field returns the literal `{}` rather than
  // the inner-default-applied shape. To compare populated shapes against the
  // cortex side, pass each cross-cutting block as an explicit `{}` so Zod
  // re-parses it through the inner schema and the inner defaults apply.
  const bot = AgentConfigSchema.parse({
    agent: { name: "x", displayName: "x" },
    discord: [],
    claude: {},
    attachments: {},
    execution: {},
    github: {},
    paths: {},
  });

  test("claude defaults match", () => {
    expect(ClaudeConfigSchema.parse({})).toEqual(bot.claude);
  });

  test("attachments defaults match", () => {
    expect(AttachmentsConfigSchema.parse({})).toEqual(bot.attachments);
  });

  test("execution defaults match", () => {
    expect(ExecutionConfigSchema.parse({})).toEqual(bot.execution);
  });

  test("github defaults match", () => {
    expect(GithubConfigSchema.parse({})).toEqual(bot.github);
  });

  test("agentDetection defaults match", () => {
    // Nested under github; check the inner block too so a field added inside
    // agentDetection on one side surfaces immediately rather than only via
    // the parent github diff (which `.toEqual` deep-compares, but an
    // independent assertion documents the intent).
    expect(AgentDetectionSchema.parse({})).toEqual(bot.github.agentDetection);
  });

  test("paths shape + defaults match (logDir grove/cortex divergence resolved by the XDG wave-5 state move #1903)", () => {
    const cortexPaths = PathsConfigSchema.parse({});
    // Same key set — field additions/removals would fail here.
    expect(Object.keys(cortexPaths).sort()).toEqual(Object.keys(bot.paths).sort());
    // Non-divergent fields equal.
    expect(cortexPaths.publishedEventsDir).toBe(bot.paths.publishedEventsDir);
    // XDG wave-5 (#1903): the historical `logDir` divergence (cortex → `~/.config/
    // cortex/logs`, grove → `~/.config/grove/logs`) is RESOLVED — both schema
    // defaults now point at the shared metafactory STATE root, so the two sides
    // agree and `paths` mirrors fully. (This is the "MIRROR window collapsing"
    // outcome the old assertion anticipated: logs became STATE and both defaults
    // were re-pointed at the same canonical dir.)
    expect(cortexPaths.logDir).toBe("~/.local/state/metafactory/cortex/logs");
    expect(bot.paths.logDir).toBe("~/.local/state/metafactory/cortex/logs");
    expect(cortexPaths.logDir).toBe(bot.paths.logDir);
  });
});

// =============================================================================
// ADR 0001 (supersedes cortex#661) — federated accept/deny subject scope.
//
// Every `policy.federated.networks[].accept_subjects[]` / `deny_subjects[]`
// pattern MUST begin with `federated.{my-principal}.{my-stack}.` — the RECEIVING
// stack's own identity. The network is never on the wire (federated subjects
// carry `{principal}.{stack}`), so the scope is the stack's identity, NOT a
// `federated.{network_id}.` prefix (the cortex#661 grammar). The check lives at
// the top level because the principal + stack come from the `principal:` +
// `stack:` blocks, which the `policy:` sub-schema does not see.
// =============================================================================

describe("CortexConfigSchema — federated accept/deny subject scope (ADR 0001)", () => {
  // `minConfig()` has principal `andreas` and NO `stack:` block, so
  // `deriveStackId` resolves `andreas/default` → expected prefix
  // `federated.andreas.default.`.
  function withFederated(network: Record<string, unknown>) {
    return {
      ...minConfig(),
      policy: {
        federated: {
          networks: [
            {
              id: "research-collab",
              leaf_node: "leaf",
              peers: [],
              accept_subjects: [],
              deny_subjects: [],
              announce_capabilities: [],
              max_hop: 0,
              ...network,
            },
          ],
        },
      },
    };
  }

  test("rejects accept_subjects[] not prefixed with federated.{my-principal}.{my-stack}.", () => {
    // Out-of-scope subject (a stale network-id prefix is just as wrong now).
    expect(() =>
      CortexConfigSchema.parse(
        withFederated({ accept_subjects: ["federated.research-collab.>"] }),
      ),
    ).toThrow(/must begin with.*federated\.andreas\.default\./);
  });

  test("rejects accept_subjects[] with a non-federated prefix (typo guard preserved)", () => {
    expect(() =>
      CortexConfigSchema.parse(
        withFederated({ accept_subjects: ["internal.private.>"] }),
      ),
    ).toThrow(/must begin with.*federated\.andreas\.default\./);
  });

  test("rejects deny_subjects[] not prefixed with federated.{my-principal}.{my-stack}.", () => {
    expect(() =>
      CortexConfigSchema.parse(
        withFederated({
          accept_subjects: ["federated.andreas.default.>"],
          deny_subjects: ["local.andreas.>"],
        }),
      ),
    ).toThrow(/must begin with.*federated\.andreas\.default\./);
  });

  test("accepts patterns within the receiving stack's own federated.{principal}.{stack}. scope", () => {
    const parsed = CortexConfigSchema.parse(
      withFederated({
        accept_subjects: [
          "federated.andreas.default.tasks.code-review.*",
          "federated.andreas.default.>",
        ],
        deny_subjects: ["federated.andreas.default.tasks.*.private.*"],
      }),
    );
    expect(parsed.policy?.federated?.networks[0]?.accept_subjects).toHaveLength(2);
  });

  test("the exported scope predicate agrees with the schema (the rule network join enforces before write, #1220)", () => {
    // `isFederatedSubjectInOwnScope` is the SINGLE rule the boot validator (this
    // schema) AND `network join`'s validate-before-write both use, so a subject
    // the join persists can never be one the daemon then rejects (#1220).
    const own = "federated.andreas.default.>";
    const peer = "federated.jc.sage-host.agent.>"; // the #1220 peer PRESENCE subtree

    // Predicate: own in scope, peer out of scope.
    expect(ownFederatedSubjectScopePrefix("andreas", "default")).toBe("federated.andreas.default.");
    expect(isFederatedSubjectInOwnScope(own, "andreas", "default")).toBe(true);
    expect(isFederatedSubjectInOwnScope(peer, "andreas", "default")).toBe(false);

    // Schema AGREES: the own subtree parses; the peer subtree is rejected — the
    // join guard (predicate) refuses exactly what CortexConfigSchema refuses.
    expect(() => CortexConfigSchema.parse(withFederated({ accept_subjects: [own] }))).not.toThrow();
    expect(() =>
      CortexConfigSchema.parse(withFederated({ accept_subjects: [peer] })),
    ).toThrow(/must begin with.*federated\.andreas\.default\./);
  });

  // P3 (cortex#1088, OQ1) — per-network reconcile opt-in.
  test("reconcile block is OPTIONAL — absent ⇒ undefined (default OFF)", () => {
    const parsed = CortexConfigSchema.parse(withFederated({}));
    expect(parsed.policy?.federated?.networks[0]?.reconcile).toBeUndefined();
  });

  test("reconcile defaults enabled:false + interval_ms:60000 when block present but partial", () => {
    const parsed = CortexConfigSchema.parse(withFederated({ reconcile: {} }));
    const reconcile = parsed.policy?.federated?.networks[0]?.reconcile;
    expect(reconcile?.enabled).toBe(false);
    expect(reconcile?.interval_ms).toBe(60000);
  });

  test("reconcile accepts an explicit enable + custom interval", () => {
    const parsed = CortexConfigSchema.parse(
      withFederated({ reconcile: { enabled: true, interval_ms: 30000 } }),
    );
    const reconcile = parsed.policy?.federated?.networks[0]?.reconcile;
    expect(reconcile?.enabled).toBe(true);
    expect(reconcile?.interval_ms).toBe(30000);
  });

  test("reconcile.interval_ms is floored at 5000 (anti-hammer)", () => {
    expect(() =>
      CortexConfigSchema.parse(
        withFederated({ reconcile: { enabled: true, interval_ms: 1000 } }),
      ),
    ).toThrow();
  });

  test("reconcile rejects unknown keys (strict — typo guard)", () => {
    expect(() =>
      CortexConfigSchema.parse(
        withFederated({ reconcile: { enabled: true, intervalMs: 30000 } }),
      ),
    ).toThrow();
  });

  test("scope principal comes from principal.id, not stack.id's principal-half (override-path silent-drop guard)", () => {
    // The `deriveStackId` "override path": principal.id "andreas" runs a stack
    // whose stack.id declares a DIFFERENT principal-half "jcfischer". The runtime
    // stamps the WIRE principal from principal.id, so it subscribes/emits on
    // `federated.andreas.sage-host.…`. The accept-list scope MUST follow the wire
    // principal (andreas), NOT stack.id's principal-half (jcfischer) — otherwise
    // the validated prefix never matches the live subscription and the accept-list
    // is silently inert. The stack SEGMENT still comes from stack.id ("sage-host").
    const parsed = CortexConfigSchema.parse({
      ...minConfig(),
      principal: { id: "andreas" },
      stack: { id: "jcfischer/sage-host" },
      policy: {
        federated: {
          networks: [
            {
              id: "research-collab",
              leaf_node: "leaf",
              peers: [],
              accept_subjects: ["federated.andreas.sage-host.>"],
              deny_subjects: [],
              announce_capabilities: [],
              max_hop: 0,
            },
          ],
        },
      },
    });
    expect(parsed.policy?.federated?.networks[0]?.accept_subjects).toHaveLength(1);

    // And the jcfischer-prefixed form (stack.id's principal-half) is REJECTED —
    // it would never match the live `federated.andreas.…` subscription.
    expect(() =>
      CortexConfigSchema.parse({
        ...minConfig(),
        principal: { id: "andreas" },
        stack: { id: "jcfischer/sage-host" },
        policy: {
          federated: {
            networks: [
              {
                id: "research-collab",
                leaf_node: "leaf",
                peers: [],
                accept_subjects: ["federated.jcfischer.sage-host.>"],
                deny_subjects: [],
                announce_capabilities: [],
                max_hop: 0,
              },
            ],
          },
        },
      }),
    ).toThrow(/must begin with.*federated\.andreas\.sage-host\./);
  });

  test("scope follows an explicit stack: block (federated.{principal}.{stack}.)", () => {
    // With `stack: { id: "andreas/research" }`, the expected prefix becomes
    // `federated.andreas.research.` — a topology-independent identity scope.
    const parsed = CortexConfigSchema.parse({
      ...minConfig(),
      stack: { id: "andreas/research" },
      policy: {
        federated: {
          networks: [
            {
              id: "research-collab",
              leaf_node: "leaf",
              peers: [],
              accept_subjects: ["federated.andreas.research.>"],
              deny_subjects: [],
              announce_capabilities: [],
              max_hop: 0,
            },
          ],
        },
      },
    });
    expect(parsed.policy?.federated?.networks[0]?.accept_subjects).toHaveLength(1);
  });
});

// sage cortex#1033 round 2 (blocker) — exec-brain capability ids are exact
// NATS subject segments; wildcards must fail at LOAD.
describe("round-2: exec-brain capability wildcard rejection", () => {
  const base = {
    mode: "in-process",
    capabilities: ["soc.compose.flow"],
    brain: { kind: "exec", run: "bun {pack}/brain/main.ts" },
  };

  test("wildcard '>' in capabilities rejected for exec brains", () => {
    const r = AgentRuntimeSchema.safeParse({ ...base, capabilities: [">"] });
    expect(r.success).toBe(false);
  });

  test("'soc.>' rejected; '*' rejected", () => {
    expect(AgentRuntimeSchema.safeParse({ ...base, capabilities: ["soc.>"] }).success).toBe(false);
    expect(AgentRuntimeSchema.safeParse({ ...base, capabilities: ["*"] }).success).toBe(false);
  });

  test("wildcard in dispatch_capabilities rejected", () => {
    const r = AgentRuntimeSchema.safeParse({
      ...base,
      brain: { ...base.brain, dispatch_capabilities: ["soc.>"] },
    });
    expect(r.success).toBe(false);
  });

  test("valid ids still pass; builtin agents unaffected by the grammar gate", () => {
    expect(AgentRuntimeSchema.safeParse(base).success).toBe(true);
    expect(
      AgentRuntimeSchema.safeParse({ mode: "in-process", capabilities: ["WEIRD CAPS"] }).success,
    ).toBe(true); // builtin: legacy looseness preserved
  });
});

describe("DiscordNotifyTargetSchema (F-6 notify.discord)", () => {
  test("accepts repo + webhook_url_env (secret reference, not the URL)", () => {
    expect(
      DiscordNotifyTargetSchema.safeParse({
        repo: "jc/reflex",
        webhook_url_env: "DISCORD_WEBHOOK_REFLEX",
      }).success,
    ).toBe(true);
  });
  test("rejects a raw webhook_url (must be an env binding, not the secret)", () => {
    expect(
      DiscordNotifyTargetSchema.safeParse({
        repo: "jc/reflex",
        webhook_url: "https://discord.com/api/webhooks/123/abc",
      }).success,
    ).toBe(false);
  });
});

describe("ReflexTargetSchema (F-6 prompt XOR handler)", () => {
  const base = { target: "@jc/notify-discord", capability: "notify.discord", assistant: "luna" };
  test("accepts a prompt-only (CC) target", () => {
    expect(ReflexTargetSchema.safeParse({ ...base, prompt: "do it" }).success).toBe(true);
  });
  test("accepts a handler-only (code) target", () => {
    expect(ReflexTargetSchema.safeParse({ ...base, handler: "discord-webhook" }).success).toBe(true);
  });
  test("rejects neither prompt nor handler", () => {
    expect(ReflexTargetSchema.safeParse(base).success).toBe(false);
  });
  test("rejects both prompt and handler", () => {
    expect(
      ReflexTargetSchema.safeParse({ ...base, prompt: "x", handler: "discord-webhook" }).success,
    ).toBe(false);
  });

  // Third channel: review-consumer dispatch (review: true).
  const reviewBase = { target: "@jc/sage-pr-review", capability: "code-review.typescript", assistant: "sage" };
  test("accepts a review-only target with a flavored code-review capability", () => {
    expect(ReflexTargetSchema.safeParse({ ...reviewBase, review: true }).success).toBe(true);
  });
  test("accepts skip_authors on a review target", () => {
    expect(
      ReflexTargetSchema.safeParse({ ...reviewBase, review: true, skip_authors: ["jcfischer"] }).success,
    ).toBe(true);
  });
  test("rejects review combined with prompt (two channels)", () => {
    expect(ReflexTargetSchema.safeParse({ ...reviewBase, review: true, prompt: "x" }).success).toBe(false);
  });
  test("rejects review combined with handler (two channels)", () => {
    expect(
      ReflexTargetSchema.safeParse({ ...base, review: true, handler: "discord-webhook" }).success,
    ).toBe(false);
  });
  test("rejects review: true with a non-code-review capability", () => {
    expect(
      ReflexTargetSchema.safeParse({ ...base, capability: "notify.discord", review: true }).success,
    ).toBe(false);
  });
  test("rejects review: false (literal-true guard — no silent extra field)", () => {
    // `review: false` + prompt must NOT slip through as a prompt-only target.
    expect(ReflexTargetSchema.safeParse({ ...base, prompt: "x", review: false }).success).toBe(false);
  });
  test("rejects review: true with a bare/unknown-flavor code-review capability", () => {
    expect(ReflexTargetSchema.safeParse({ ...reviewBase, capability: "code-review", review: true }).success).toBe(false);
    expect(ReflexTargetSchema.safeParse({ ...reviewBase, capability: "code-review.elvish", review: true }).success).toBe(false);
  });
});
