#!/usr/bin/env bun
/**
 * `cortex normalize-config` — rename legacy v3 vocabulary keys in a cortex.yaml
 * to their v4 canonical equivalents.
 *
 * WHY THIS EXISTS
 * ---------------
 * cortex v4.0.0 was a clean break: the transition-era config-key aliases
 * (e.g. `home_operator` accepted alongside `home_principal`) were removed from
 * `PolicyPrincipalSchema`. Configs that passed `migrate-config` under v3 but
 * still carry the old unambiguous key now fail v4 schema parse. Rather than
 * adding permanent loader aliases (which locks in technical debt forever), this
 * one-time normaliser renames the safe unambiguous keys in-place so the config
 * becomes canonical v4 before the process starts.
 *
 * JC CASE (cortex#564)
 * --------------------
 * `policy.principals[].home_operator` is the key that blocked JC's v4 upgrade —
 * a clearly one-to-one rename (`home_operator` → `home_principal`) that is safe
 * to apply mechanically without any principal judgment.
 *
 * RENAME MAP EXTENSIBILITY
 * ------------------------
 * `UNAMBIGUOUS_RENAME_MAP` is the single authoritative source for safe key renames.
 * It is seeded with `home_operator` only. Future unambiguous legacy keys can be
 * added here without changing the walk logic. "Unambiguous" means the old key
 * has exactly one valid migration target and zero NSC/NATS/platform-level
 * homonyms — the rename is always safe regardless of context.
 *
 * WARN-DON'T-RENAME FOR AMBIGUOUS KEYS
 * --------------------------------------
 * Some keys look like legacy vocab but carry multiple meanings:
 *   - A top-level `operator:` block may be NSC operator config or a transition
 *     `principal:` alias depending on context; the correct action is human review
 *     followed by `migrate-config` / `migrate-config-policy`.
 *   - `operatorId` may be a v2 cloud field or an NSC identity; context matters.
 * This tool detects these and emits warnings directing the principal to the
 * appropriate migration tool. It NEVER auto-renames ambiguous keys.
 *
 * Usage:
 *   bun src/cli/cortex/commands/normalize-config.ts <cortex.yaml> [--out FILE] [--check] [--strict]
 *
 * Flags:
 *   --out FILE     Write to FILE instead of overwriting the input (no backup needed)
 *   --check        Report what would change + validate; do NOT write
 *   --strict       Treat ambiguous-key warnings as failures (exit 2)
 *   -h, --help     Show this help
 *
 * Exit codes:
 *   0  — normalized successfully (or idempotent — nothing to change)
 *   1  — failure (read error, YAML parse error, schema validation failed)
 *   2  — strict-mode warnings (ambiguous legacy keys detected with --strict)
 */

import { readFileSync, writeFileSync } from "fs";
import { resolve } from "path";
import YAML from "yaml";

import { CortexConfigSchema } from "../../../common/types/cortex-config";

// =============================================================================
// Rename map — safe, unambiguous, one-to-one key renames
// =============================================================================

/**
 * Maps a legacy key name to its v4 canonical replacement. Only EXACT key
 * matches are renamed — substrings, identifiers, and values are never touched.
 *
 * Add entries here as new unambiguous renames are identified. Each entry MUST
 * satisfy:
 *   1. The old key has exactly one safe migration target.
 *   2. The rename is safe in ALL config contexts (no NSC/NATS homonyms).
 *   3. The old key is not an ambiguous term (those go to AMBIGUOUS_KEY_WARNINGS).
 */
const UNAMBIGUOUS_RENAME_MAP: Readonly<Record<string, string>> = {
  // R2.J — `home_operator` was removed from PolicyPrincipalSchema at v4.0.0.
  // The field appeared in `policy.principals[]` blocks generated by the v3
  // migrate-config-policy path. Canonical replacement is `home_principal`.
  // cortex#564 — JC's upgrade snag.
  // eslint-disable-next-line @typescript-eslint/naming-convention
  "home_operator": "home_principal",
};

// =============================================================================
// Ambiguous key detection — warn but never rename
// =============================================================================

/**
 * Describes a legacy key that CANNOT be safely auto-renamed because it has
 * multiple possible meanings depending on context. The normaliser warns and
 * points to the appropriate manual migration step.
 */
interface AmbiguousKeySpec {
  /** Exact key name that triggers a warning. */
  key: string;
  /** Human-readable guidance for the principal. */
  guidance: string;
}

/**
 * Keys that require human/policy judgment. These are detected at any nesting
 * depth and surfaced as warnings, never renamed.
 *
 * The top-level `operator:` block and `operatorId` are the two cases
 * documented in CONTEXT.md as needing per-site LLM review grounded in the
 * codebase domain model.
 */
const AMBIGUOUS_KEY_WARNINGS: readonly AmbiguousKeySpec[] = [
  {
    // eslint-disable-next-line @typescript-eslint/naming-convention
    key: "operatorId",
    guidance:
      "operatorId may be a v2 cloud-publisher field or an NSC identity. " +
      "Run `cortex migrate-config` or `cortex migrate-config-policy` and review " +
      "the conversion table to determine the correct rename for this deployment.",
  },
  {
    key: "operator",
    guidance:
      "A top-level `operator:` block may be NSC operator config (permanent, do not rename) " +
      "or a legacy principal block from cortex v2 (rename to `principal:`). " +
      "Run `cortex migrate-config` to convert a v2 `operator:` block, or consult " +
      "CONTEXT.md §NSC to confirm this is infrastructure config that should stay as-is.",
  },
];

// =============================================================================
// Pure normalize logic — no file I/O
// =============================================================================

/**
 * Result of a normalizeVocab call.
 *
 *   result   — the transformed object (deep clone; input is not mutated)
 *   renames  — dot-path strings of each key that was renamed, e.g.
 *              ["policy.principals[0].home_operator → home_principal"]
 *   warnings — human-readable strings for each ambiguous key detected
 */
export interface NormalizeResult {
  result: unknown;
  renames: string[];
  warnings: string[];
}

/**
 * Walk `raw` recursively and apply UNAMBIGUOUS_RENAME_MAP to every object key
 * at every depth. Detects AMBIGUOUS_KEY_WARNINGS and accumulates warnings.
 *
 * Pure function — no file I/O, no side effects. Safe to call in tests.
 *
 * @param raw      The parsed YAML object (any shape — validated separately)
 * @returns        { result, renames, warnings } — see NormalizeResult above
 */
export function normalizeVocab(raw: unknown): NormalizeResult {
  const renames: string[] = [];
  const warnings: string[] = [];

  function walk(node: unknown, path: string): unknown {
    if (Array.isArray(node)) {
      return node.map((item, idx) => walk(item, `${path}[${idx}]`));
    }
    if (node !== null && typeof node === "object") {
      const src = node as Record<string, unknown>;
      const out: Record<string, unknown> = {};
      for (const [k, v] of Object.entries(src)) {
        // Check for ambiguous keys first (never rename these, only warn).
        // We warn once per top-level `operator` key at this node, not per
        // every nested occurrence — the ambiguous specs are for exact keys
        // that ONLY appear in specific structural positions. We do still
        // recurse into them so child renames (e.g. home_operator inside a
        // deeply-nested structure next to an operator key) are applied.
        const ambiguous = AMBIGUOUS_KEY_WARNINGS.find((s) => s.key === k);
        if (ambiguous !== undefined) {
          const pathLabel = path ? `${path}.${k}` : k;
          warnings.push(`Ambiguous legacy key "${k}" at ${pathLabel}: ${ambiguous.guidance}`);
          out[k] = walk(v, `${path}${path ? "." : ""}${k}`);
          continue;
        }

        // Check for unambiguous rename.
        const canonical = UNAMBIGUOUS_RENAME_MAP[k];
        if (canonical !== undefined) {
          const fromPath = path ? `${path}.${k}` : k;
          // Collision guard: if the canonical target key ALSO exists in this
          // same object, renaming would silently overwrite one value
          // (last-writer-wins). We check `src` (not `out`) so the result is
          // independent of key iteration order. Refuse the rename — warn and
          // keep the legacy key untouched so the conflict surfaces (to the
          // operator + schema validation) instead of losing data silently.
          if (canonical in src) {
            warnings.push(
              `Key collision at ${fromPath}: both "${k}" and "${canonical}" exist in the same block — ` +
                `NOT renaming (would overwrite "${canonical}"). Resolve manually: keep "${canonical}" and remove "${k}".`,
            );
            out[k] = walk(v, fromPath);
          } else {
            const toPath = path ? `${path}.${canonical}` : canonical;
            renames.push(`${fromPath} → ${toPath}`);
            out[canonical] = walk(v, toPath);
          }
        } else {
          out[k] = walk(v, path ? `${path}.${k}` : k);
        }
      }
      return out;
    }
    // Primitive — returned as-is (values are never renamed).
    return node;
  }

  const result = walk(raw, "");
  return { result, renames, warnings };
}

// =============================================================================
// CLI argument parsing
// =============================================================================

interface ParsedArgs {
  input: string | undefined;
  out: string | undefined;
  check: boolean;
  strict: boolean;
  help: boolean;
}

/**
 * Hand-rolled arg parser — mirrors migrate-config.ts pattern; no Commander
 * dependency. Positional = input file, named flags as documented in the file
 * header. Throws on unrecognised flags so the caller can surface a clean error.
 */
export function parseArgs(argv: string[]): ParsedArgs {
  const args: ParsedArgs = {
    input: undefined,
    out: undefined,
    check: false,
    strict: false,
    help: false,
  };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i] ?? "";
    if (a === "--help" || a === "-h") {
      args.help = true;
    } else if (a === "--check") {
      args.check = true;
    } else if (a === "--strict") {
      args.strict = true;
    } else if (a === "--out") {
      const next = argv[i + 1];
      if (next === undefined || next.startsWith("--")) {
        throw new Error("--out requires a path argument");
      }
      args.out = next;
      i++;
    } else if (a.startsWith("--out=")) {
      args.out = a.slice("--out=".length);
    } else if (a.startsWith("--")) {
      throw new Error(`unknown flag: ${a}`);
    } else if (args.input === undefined) {
      args.input = a;
    } else {
      throw new Error(`unexpected positional argument: ${a}`);
    }
  }
  return args;
}

// =============================================================================
// Help text
// =============================================================================

function printHelp(): void {
  console.log(
    "cortex normalize-config — rename unambiguous legacy v3 keys in a cortex.yaml\n",
  );
  console.log("Usage:");
  console.log(
    "  bun src/cli/cortex/commands/normalize-config.ts <cortex.yaml> [options]\n",
  );
  console.log("Options:");
  console.log("  --out FILE   Write to FILE (default: overwrite input with backup)");
  console.log("  --check      Report changes + validate; do NOT write");
  console.log(
    "  --strict     Fail (exit 2) when ambiguous legacy keys are detected",
  );
  console.log("  -h, --help   Show this help");
}

// =============================================================================
// Timestamped backup helper
// =============================================================================

/**
 * Build a backup path for `filePath` using the current wall-clock time.
 * Format: `<filePath>.pre-normalize-<YYYYMMDDTHHMMSS>.bak`
 *
 * Mirrors the style used by migrate-config for consistency so principals
 * have one predictable backup naming scheme across all cortex migration tools.
 */
function buildBackupPath(filePath: string): string {
  const now = new Date();
  const pad = (n: number): string => String(n).padStart(2, "0");
  const stamp = [
    now.getFullYear(),
    pad(now.getMonth() + 1),
    pad(now.getDate()),
    "T",
    pad(now.getHours()),
    pad(now.getMinutes()),
    pad(now.getSeconds()),
  ].join("");
  return `${filePath}.pre-normalize-${stamp}.bak`;
}

// =============================================================================
// Main — exported for testing
// =============================================================================

/**
 * Run the normalize-config workflow. Exported so the in-process test harness
 * can call it without spawning a subprocess. The bottom of this file calls it
 * from `process.argv` when the script is executed directly.
 *
 * @param argv  Arguments following the script name (i.e. process.argv.slice(2))
 * @returns     Exit code: 0 ok | 1 fail | 2 strict-mode warnings
 */
// eslint-disable-next-line @typescript-eslint/require-await
export async function runNormalizeConfig(argv: string[]): Promise<number> {
  let args: ParsedArgs;
  try {
    args = parseArgs(argv);
  } catch (err) {
    process.stderr.write(
      `Error: ${err instanceof Error ? err.message : String(err)}\n`,
    );
    printHelp();
    return 1;
  }

  if (args.help) {
    printHelp();
    return 0;
  }

  if (!args.input) {
    process.stderr.write("Error: <cortex.yaml> is required\n\n");
    printHelp();
    return 1;
  }

  const inputPath = resolve(args.input);
  let rawYaml: string;
  try {
    rawYaml = readFileSync(inputPath, "utf-8");
  } catch (err) {
    process.stderr.write(
      `Error: cannot read ${inputPath}: ${err instanceof Error ? err.message : String(err)}\n`,
    );
    return 1;
  }

  let parsed: unknown;
  try {
    parsed = YAML.parse(rawYaml);
  } catch (err) {
    process.stderr.write(
      `Error: invalid YAML in ${inputPath}: ${err instanceof Error ? err.message : String(err)}\n`,
    );
    return 1;
  }

  const { result, renames, warnings } = normalizeVocab(parsed);

  // Emit warnings regardless of mode so principals always see them.
  for (const w of warnings) {
    process.stderr.write(`warning: ${w}\n`);
  }

  if (renames.length === 0) {
    // No unambiguous renames → nothing to write. Even when ambiguous keys were
    // warned above, the vocabulary is unchanged, so we must NOT reformat the
    // file or drop a backup (that would falsely signal a modification).
    if (warnings.length === 0) {
      process.stderr.write(`normalize-config: no legacy keys found in ${inputPath} — nothing to do\n`);
    } else {
      process.stderr.write(
        `normalize-config: no unambiguous renames; ${warnings.length} ambiguous key(s) warned above — ` +
          `review manually (see 'cortex migrate-config'). Nothing written.\n`,
      );
    }
    return args.strict && warnings.length > 0 ? 2 : 0;
  }

  process.stderr.write(`normalize-config: ${renames.length} key(s) to rename:\n`);
  for (const r of renames) {
    process.stderr.write(`  ${r}\n`);
  }

  // Validate the normalized output against the schema BEFORE writing.
  // If it still fails (e.g. unresolved ambiguous keys, missing required fields),
  // surface the Zod error and exit 1 rather than writing a broken config.
  const validation = CortexConfigSchema.safeParse(result);
  if (!validation.success) {
    process.stderr.write(
      `normalize-config: schema validation failed after rename — NOT writing output.\n` +
      `  Zod error: ${validation.error.message}\n` +
      `  Hint: if ambiguous legacy keys are blocking validation, run 'cortex migrate-config' first.\n`,
    );
    return 1;
  }

  // --check mode: report only, no write.
  if (args.check) {
    process.stderr.write(
      `normalize-config --check: would rename ${renames.length} key(s), schema validation PASSED\n`,
    );
    if (args.strict && warnings.length > 0) {
      return 2;
    }
    return 0;
  }

  const yamlOut = YAML.stringify(result, { indent: 2, lineWidth: 0 });

  if (args.out) {
    // Write to --out target: no backup needed (input is not modified).
    const outPath = resolve(args.out);
    try {
      writeFileSync(outPath, yamlOut, "utf-8");
      process.stderr.write(`normalize-config: wrote ${outPath}\n`);
    } catch (err) {
      process.stderr.write(
        `Error: cannot write ${outPath}: ${err instanceof Error ? err.message : String(err)}\n`,
      );
      return 1;
    }
  } else {
    // Overwrite input in-place with a timestamped backup.
    const backupPath = buildBackupPath(inputPath);
    try {
      writeFileSync(backupPath, rawYaml, "utf-8");
      process.stderr.write(`normalize-config: backup saved to ${backupPath}\n`);
    } catch (err) {
      process.stderr.write(
        `Error: cannot write backup ${backupPath}: ${err instanceof Error ? err.message : String(err)}\n`,
      );
      return 1;
    }
    try {
      writeFileSync(inputPath, yamlOut, "utf-8");
      process.stderr.write(`normalize-config: wrote ${inputPath}\n`);
    } catch (err) {
      process.stderr.write(
        `Error: cannot write ${inputPath}: ${err instanceof Error ? err.message : String(err)}\n`,
      );
      return 1;
    }
  }

  if (args.strict && warnings.length > 0) {
    return 2;
  }
  return 0;
}

// =============================================================================
// Entry point
// =============================================================================

if (import.meta.main) {
  runNormalizeConfig(process.argv.slice(2)).then(
    (code) => { process.exit(code); },
    (err: unknown) => {
      process.stderr.write(`Fatal: ${String(err)}\n`);
      process.exit(1);
    },
  );
}
